/**
 * Unit contract of every ported analyzer module.
 *
 * Parity (`parity.test.ts`) proves the whole pipeline matches the engine byte for byte, but a
 * byte-equal pipeline can still hide dead branches that no fixture exercised. These tests pin the
 * interesting internals directly — classifier edge cases, resolution precedence, validation
 * messages, threshold arithmetic — so a future edit fails here before it can silently change a
 * verdict somewhere else.
 */
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';
import ts from 'typescript';
import {
	collectSourceFiles,
	describeRoots,
	isTestPath,
	lineCounts,
	scannerInputInventory
} from '../../build/analysis/inventory.js';
import {
	exportedStems,
	moduleMappings,
	mappedStems,
	packageFor,
	resolveImport,
	resolveStem,
	stronglyConnected,
	testReach
} from '../../build/analysis/graph.js';
import {
	conceptFor,
	pillarFor,
	importLocality,
	localityScore,
	emptyLocality
} from '../../build/analysis/structure.js';
import { SCANNER_VERSION, staticFindings } from '../../build/analysis/authenticate.js';
import {
	analyzeAst,
	complexityOf,
	indirectionFindings,
	isPassThrough
} from '../../build/analysis/complexity.js';
import { LANGUAGE_HEALTH_PROFILE, mergeHealthProfile } from '../../build/health-profile.js';
import {
	pathwayHash,
	shingleSimilarity,
	pathwayEvidence,
	clusterLabel
} from '../../build/analysis/entities.js';
import { isConfiguredTest } from '../../build/analysis/tests-config.js';
import { compare, distribution, roundedRatio } from '../../build/analysis/composite.js';
import { markdown, pairedOutputRoot } from '../../build/analysis/report.js';

function scratch(prefix: string): string {
	return mkdtempSync(join(tmpdir(), `${prefix}-`));
}

function writeTree(root: string, tree: Record<string, string>): void {
	for (const [name, content] of Object.entries(tree)) {
		const path = join(root, name);
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, content);
	}
}

// --- inventory ------------------------------------------------------------------------------

test('inventory: script LOC keeps template-literal markers as code', () => {
	const source = [
		'const banner = `// not a comment`;',
		'// real comment',
		'/* block',
		'still block */ const after = 1;',
		''
	].join('\n');
	const counts = lineCounts('src/a.ts', source);
	assert.equal(counts.physical, 4);
	assert.equal(counts.code, 2);
	assert.equal(counts.comments, 2);
	assert.equal(counts.blank, 0);
});

test('inventory: svelte LOC treats quoted markup comments as code', () => {
	const source = [
		'<script>',
		'	const marker = "<!-- stays code -->";',
		'	// real script comment',
		'</script>',
		'<!-- page comment',
		'spanning lines -->',
		'<div>{marker}</div>',
		''
	].join('\n');
	const counts = lineCounts('src/b.svelte', source);
	assert.equal(counts.physical, 7);
	assert.equal(counts.comments, 3);
	assert.equal(counts.code, 4);
});

test('inventory: discovery excludes dependency trees, declarations, and generated headers', () => {
	const root = scratch('doctor-inv');
	writeTree(root, {
		'.doctorignore': 'archived/\n',
		'src/keep.ts': 'export const keep = 1;\n',
		'src/legacy.d.ts': 'export declare const legacy: number;\n',
		'src/generated.ts': '// @generated by the framework\nexport const g = 1;\n',
		'src/part.generated.ts': 'export const part = 1;\n',
		'node_modules/pkg/index.js': 'module.exports = 1;\n',
		'dist/bundle.js': 'export {};',
		'archived/old.ts': 'export const old = 1;\n'
	});
	try {
		const files = collectSourceFiles([root]).map((file) => file.slice(root.length + 1));
		assert.deepEqual(files, [join('src', 'keep.ts')]);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test('inventory: root identities hash only on basename collisions', () => {
	const [single] = describeRoots(['/tmp/alpha']);
	assert.equal(single?.id, 'alpha');
	const [first, second] = describeRoots(['/tmp/team', '/other/team']);
	assert.ok(first && second);
	assert.notEqual(first.id, second.id);
	assert.equal(first.id.startsWith('team-'), true);
});

test('inventory: scanner digest tracks input bytes, not walk order', () => {
	const root = scratch('doctor-digest');
	writeTree(root, { 'a.ts': 'export const a = 1;\n', 'sub/b.mjs': 'export const b = 2;\n' });
	try {
		const first = scannerInputInventory(root);
		const second = scannerInputInventory(root);
		assert.deepEqual(first.sources, ['a.ts', 'sub/b.mjs']);
		assert.deepEqual(first.inputs, ['.doctorignore', 'a.ts', 'sub/b.mjs'].filter((name) => name !== '.doctorignore'));
		assert.equal(first.digest, second.digest);
		assert.match(first.digest, /^sha256:[0-9a-f]{64}$/);
		writeFileSync(join(root, 'a.ts'), 'export const a = 2;\n');
		assert.notEqual(scannerInputInventory(root).digest, first.digest);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test('inventory: test paths are recognized by directory and suffix', () => {
	assert.equal(isTestPath('/repo/test/setup.ts'), true);
	assert.equal(isTestPath('/repo/src/login.spec.ts'), true);
	assert.equal(isTestPath('/repo/e2e/login.ts'), true);
	assert.equal(isTestPath('/repo/src/testing.ts'), false);
	assert.equal(isTestPath('/repo/src/spec.ts'), false);
});

// --- graph ----------------------------------------------------------------------------------

test('graph: stems probe extensions, index files, and strip Vite suffixes', () => {
	const fileSet = new Set(['/r/src/panel.ts', '/r/src/box/index.ts']);
	assert.equal(resolveStem('/r/src/panel.js?import', fileSet), '/r/src/panel.ts');
	assert.equal(resolveStem('/r/src/box', fileSet), '/r/src/box/index.ts');
	assert.equal(resolveStem('/r/src/absent.ts', fileSet), undefined);
});

const OWNER = {
	root: '/r/packages/lib',
	name: '@ws/lib',
	scanRoot: '/r',
	id: 'lib/@ws/lib@packages/lib'
};

test('graph: exports flatten conditionals and project build output back to source', () => {
	const root = scratch('doctor-exports');
	writeTree(root, {
		'package.json': `${JSON.stringify({
			name: '@ws/lib',
			exports: {
				'.': {
					import: './dist/index.js',
					require: './dist/index.cjs'
				},
				'./*': './build/*.js'
			}
		})}\n`,
		'src/index.ts': 'export {};\n'
	});
	try {
		const owner = { ...OWNER, root };
		// Both conditional branches survive as separate stems, stripped of build output and
		// extensions; dedup happens later, at resolved-target level.
		assert.deepEqual(exportedStems(owner, ''), [
			join(root, 'src/index'),
			join(root, 'src/index')
		]);
		assert.deepEqual(exportedStems(owner, 'util'), [join(root, 'src/util')]);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test('graph: alias mappings come from manifest imports and compiler paths', () => {
	const root = scratch('doctor-aliases');
	writeTree(root, {
		'package.json': `${JSON.stringify({ name: '@ws/lib', imports: { '#lib/*': './build/*.js', '#env': './src/env.ts' } })}\n`,
		'tsconfig.json': `${JSON.stringify({ compilerOptions: { baseUrl: '.', paths: { '@/*': ['./src/*'] } } })}\n`
	});
	try {
		const owner = { ...OWNER, root, scanRoot: root };
		const mappings = moduleMappings(owner);
		// Longest fixed part first: `#lib/*` beats `#env`, compiler paths follow manifest imports.
		assert.deepEqual(
			mappings.map(({ pattern }) => pattern),
			['#lib/*', '#env', '@/*']
		);
		const star = mappings[0];
		if (!star) throw new Error('missing #lib mapping');
		assert.deepEqual(mappedStems('#lib/math', star), [join(root, 'src/math')]);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test('graph: package ownership tolerates unreadable manifests and caches directories', () => {
	const root = scratch('doctor-owner');
	writeTree(root, {
		'package.json': '{ broken',
		'packages/lib/package.json': `${JSON.stringify({ name: '@ws/lib' })}\n`,
		'packages/lib/src/deep/file.ts': 'export {};\n'
	});
	try {
		const cache = new Map<string, ReturnType<typeof packageFor>>();
		const deep = join(root, 'packages/lib/src/deep/file.ts');
		const owner = packageFor(deep, root, 'rid', cache);
		assert.equal(owner?.name, '@ws/lib');
		assert.equal(owner?.id, 'rid/@ws/lib@packages/lib');
		const parent = packageFor(join(root, 'packages/lib/src/other.ts'), root, 'rid', cache);
		assert.equal(parent?.id, owner?.id);
		const bare = packageFor(join(root, 'scripts/run.ts'), root, 'rid', new Map());
		assert.equal(bare?.id, `rid/${root.split('/').at(-1)}@.`);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test('graph: resolution classifies internal, external, aliased, and workspace specifiers', () => {
	const root = scratch('doctor-resolve');
	writeTree(root, {
		'packages/lib/package.json': `${JSON.stringify({
			name: '@ws/lib',
			exports: { './util': './src/util.ts' }
		})}\n`,
		'packages/lib/src/util.ts': 'export const util = 1;\n',
		'packages/app/src/main.ts': 'export {};\n'
	});
	try {
		const app = {
			root: join(root, 'packages/app'),
			name: '@ws/app',
			scanRoot: root,
			id: 'rid/@ws/app@packages/app'
		};
		const libOwner = {
			root: join(root, 'packages/lib'),
			name: '@ws/lib',
			scanRoot: root,
			id: 'rid/@ws/lib@packages/lib'
		};
		const fileSet = new Set([join(root, 'packages/app/src/main.ts'), join(root, 'packages/lib/src/util.ts')]);
		const aliasesByRoot = new Map([[app.root, [{ pattern: '@app/*', targets: [join(app.root, 'src', '*')], order: 0 }]]]);
		const packageByName = new Map([['@ws/lib', [libOwner]]]);
		const resolved = resolveImport(
			join(app.root, 'src/main.ts'),
			'./main.ts',
			fileSet,
			packageByName,
			app,
			new Map()
		);
		assert.deepEqual(resolved.targets, [join(app.root, 'src/main.ts')]);
		assert.equal(resolved.internal, true);

		const workspace = resolveImport(
			join(app.root, 'src/main.ts'),
			'@ws/lib/util',
			fileSet,
			packageByName,
			app,
			new Map()
		);
		assert.deepEqual(workspace.targets, [join(root, 'packages/lib/src/util.ts')]);

		const dollarLib = resolveImport(
			join(app.root, 'src/main.ts'),
			'$lib/maths',
			fileSet,
			packageByName,
			libOwner,
			new Map()
		);
		assert.equal(dollarLib.internal, true);
		assert.deepEqual(dollarLib.targets, []);

		const hash = resolveImport(
			join(libOwner.root, 'src/util.ts'),
			'#internal/thing',
			fileSet,
			packageByName,
			libOwner,
			new Map()
		);
		assert.equal(hash.internal, true);
		assert.deepEqual(hash.targets, []);

		const external = resolveImport(
			join(app.root, 'src/main.ts'),
			'effect',
			fileSet,
			packageByName,
			app,
			new Map()
		);
		assert.equal(external.internal, false);

		const aliased = resolveImport(
			join(app.root, 'src/main.ts'),
			'@app/main.ts',
			fileSet,
			packageByName,
			app,
			aliasesByRoot
		);
		assert.deepEqual(aliased.targets, [join(app.root, 'src/main.ts')]);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test('graph: Tarjan reports cycles deterministically, including self-loops', () => {
	const nodes = new Set(['/a', '/b', '/c', '/d']);
	const adjacency = new Map<string, Set<string>>([
		['/a', new Set(['/b'])],
		['/b', new Set(['/a'])],
		['/c', new Set(['/c'])],
		['/d', new Set()]
	]);
	const components = stronglyConnected(nodes, adjacency);
	assert.deepEqual(components, [['/a', '/b'], ['/c']]);
});

test('graph: reach follows value edges from configured tests only', () => {
	const adjacency = new Map<string, Set<string>>([
		['/t.test.ts', new Set(['/prod.ts', '/types.d.ts'])],
		['/prod.ts', new Set(['/leaf.ts'])]
	]);
	const productionSet = new Set(['/prod.ts', '/leaf.ts']);
	assert.deepEqual([...testReach(new Set(['/t.test.ts']), adjacency, productionSet)].sort(), ['/leaf.ts', '/prod.ts']);
});

// --- structure ------------------------------------------------------------------------------

test('structure: concepts take two directories under src; pillars take the first', () => {
	const owner = { root: '/r/pkg', name: 'pkg', scanRoot: '/r', id: 'r/pkg@pkg' };
	const nested = conceptFor('/r/pkg/src/a/b/c/file.ts', owner);
	assert.equal(nested, 'r/pkg@pkg:a/b');
	assert.equal(pillarFor('/r/pkg/src/a/b/c/file.ts', owner), 'r/pkg@pkg:a');
	assert.equal(conceptFor('/r/pkg/lib/file.ts', owner), 'r/pkg@pkg:lib');
	assert.equal(pillarFor('/r/pkg/src/file.ts', owner), 'r/pkg@pkg:root');
});

const LOCAL_FROM = {
	root: { id: 'r' },
	owner: { id: 'r/pkg@pkg' },
	path: '/r/pkg/src/one/mod.ts',
	concept: 'c1',
	pillar: 'p1'
};

function localTarget(path: string, overrides: Partial<typeof LOCAL_FROM> = {}): typeof LOCAL_FROM {
	const target = { ...LOCAL_FROM, path, ...overrides };
	return target;
}

test('structure: locality classes span same-directory through cross-root', () => {
	assert.equal(importLocality(LOCAL_FROM, localTarget('/r/pkg/src/one/other.ts')), 'sameDirectory');
	assert.equal(importLocality(LOCAL_FROM, localTarget('/r/pkg/src/one/deep/x.ts')), 'parentChild');
	assert.equal(importLocality(LOCAL_FROM, localTarget('/r/pkg/src/up.ts')), 'parentChild');
	assert.equal(
		importLocality(LOCAL_FROM, localTarget('/r/pkg/src/two/x.ts', { concept: 'c2' })),
		'samePillar'
	);
	assert.equal(
		importLocality(LOCAL_FROM, localTarget('/r/pkg/src/two/x.ts', { concept: 'c1', pillar: 'p2' })),
		'sameConcept'
	);
	assert.equal(
		importLocality(LOCAL_FROM, localTarget('/r/pkg/other/x.ts', { owner: { id: 'r/other@other' }, pillar: 'p9', concept: 'c9' })),
		'crossPackage'
	);
	assert.equal(importLocality(LOCAL_FROM, localTarget('/s/x.ts', { root: { id: 's' }, owner: { id: 's/o@o' }, pillar: 'p8', concept: 'c8' })), 'crossRoot');
});

test('structure: colocation score weights classes and defaults to perfect when empty', () => {
	assert.equal(localityScore(emptyLocality()), 100);
	const counts = emptyLocality();
	counts.sameDirectory = 1;
	counts.crossPackage = 1;
	assert.equal(localityScore(counts), Math.round(((1 * 1 + 0.1 * 1) / 2) * 100 * 1_000_000) / 1_000_000);
});

// --- authenticate ---------------------------------------------------------------------------

test('authenticate: catalogue rows attach to records and unmapped locations stay visible', () => {
	const receipt = {
		root: '/r',
		sourceInventoryDigest: 'sha256:' + 'aa'.repeat(32),
		ruleSetDigest: 'sha256:' + 'bb'.repeat(32),
		catalogueDigest: 'sha256:' + 'cc'.repeat(32)
	};
	const quality = staticFindings(
		[{ receiptPath: '/r/.norbital/diagnosis/receipt.json', receipt, catalogue: '/r/.norbital/diagnosis/findings.tsv', rows: [
			`error\thigh\tA6\tawait in loop\tsrc/one/mod.ts:12: await x(); [position=loop-body]\tstraightforwardness`,
			`hint\treview\tQ4\tnaming\toutside/nobody.ts:3: y(); [name=y]\tcolocation,no-bloat`
		] }],
		new Map([['/r/src/one/mod.ts', { displayPath: 'r/src/one/mod.ts', concept: 'r/pkg@pkg:one' }]]),
		new Map([['/r', { path: '/r', id: 'r' }]])
	);
	assert.equal(quality.totals.error, 1);
	assert.equal(quality.totals.hint, 1);
	const [mapped, unmapped] = quality.findings;
	assert.equal(mapped?.file, 'r/src/one/mod.ts');
	assert.equal(mapped?.line, 12);
	assert.equal(mapped?.concept, 'r/pkg@pkg:one');
	assert.deepEqual(mapped?.principles, ['straightforwardness']);
	assert.equal(unmapped?.file, 'r/outside/nobody.ts');
	assert.equal(unmapped?.concept, 'unmapped');
	assert.equal(unmapped?.evidence, 'name=y');
	assert.deepEqual(
		quality.byPrinciple.map(({ name, count }) => [name, count]),
		[['simplicity', 0], ['straightforwardness', 1], ['modularity', 0], ['testability', 0], ['efficiency', 0], ['type-safety', 0], ['colocation', 1], ['no-bloat', 1]]
	);
	assert.equal(SCANNER_VERSION, 34);
});

// --- complexity -----------------------------------------------------------------------------

test('complexity: branch points count once each and nested functions stop the walk', () => {
	const metrics = complexityOf(
		parseBody(`
			if (a) { while (b) {} }
			for (;;) {}
			switch (x) { case 1: break; }
			try {} catch {}
			const ternary = a ? 1 : 2;
			const both = a && b || c ?? d;
			while (a) {}
			do {} while (a);
			for (const k in o) {}
			for (const v of list) {}
			function nested() { if (deep) {} }
		`)
	);
	// Ten control nodes plus three short-circuit operators; the nested function is excluded.
	assert.equal(metrics.cyclomatic, 14);
	assert.equal(metrics.nesting, 2);

	const flat = complexityOf(parseBody('if (a) { function inner() { if (b) {} } }'));
	assert.equal(flat.cyclomatic, 2);
});

function parseBody(body: string): ts.Node {
	const wrapped = ts.createSourceFile(
		'/probe.ts',
		`function wrapper() {${body}}`,
		ts.ScriptTarget.Latest,
		true
	);
	const declaration = wrapped.statements[0] as { body: ts.Node };
	return declaration.body;
}

test('complexity: pass-through recognizes only direct forwarding shapes', () => {
	const passThrough = (source: string): boolean => {
		const file = ts.createSourceFile('/probe.ts', source, ts.ScriptTarget.Latest, true);
		let found: ts.Node | undefined;
		const visit = (node: import('typescript').Node): void => {
			if (ts.isArrowFunction(node)) found = node.body;
			ts.forEachChild(node, visit);
		};
		visit(file);
		if (!found) throw new Error('no arrow body');
		return isPassThrough(found);
	};
	assert.equal(passThrough('const a = (v) => forward(v);'), true);
	assert.equal(passThrough('const a = async (v) => await forward(v);'), true);
	assert.equal(passThrough('const a = (v) => { return wrap(v); };'), true);
	assert.equal(passThrough('const a = (v) => { transform(v); return v; };'), false);
	assert.equal(passThrough('const a = (v) => forward(v, extra);'), true);
	assert.equal(passThrough('const a = (v) => v + 1;'), false);
});

test('complexity: AST summary extracts imports, services, and inline evidence', () => {
	const source = `
import { effect } from 'effect';
import type { Clock } from 'effect';
import { effect as rename } from 'effect';
export const port = Context.GenericTag<'p'>('p');
export const generic = Context.GenericTag<'g'>('g');
export class Session extends Effect.Service<Session>() {
	static live = Effect.succeed(new Session());
}
export const layer = ServiceMap.Service<'l'>('l');
export const forward = (value) => pipe(value);
export const start = (value) => forward(value);
const internalShim = (input: string) => bridgeCall(input);
export const kickoff = (input: string) => internalShim(input);
const onReady = (value) => notify(value);
export const startReady = (value) => onReady(value);
const dynamic = () => import('./late.js');
const legacy = require('./old.cjs');
const asset = new URL('./asset.txt', import.meta.url);
export * from './reexports.js';
`;
	const realm = mergeHealthProfile(LANGUAGE_HEALTH_PROFILE, {
		serviceHeritage: [
			'(?:Effect|Context|ServiceMap)\\.Service',
			'(?:Context|ServiceMap)\\.(?:(?:Generic)?Tag|Service)\\s*(?:<[^;]+?>)?\\s*\\('
		]
	});
	assert.deepEqual(analyzeAst('/probe/store.ts', source).services, []);
	const summary = analyzeAst('/probe/store.ts', source, realm);
	assert.deepEqual(
		summary.imports.map(({ specifier, typeOnly }) => [specifier, typeOnly]),
		[
			['./asset.txt', false],
			['./late.js', false],
			['./old.cjs', false],
			['./reexports.js', false],
			['effect', false],
			['effect', true]
		]
	);
	assert.deepEqual(summary.services.sort(), ['generic', 'layer', 'port', 'Session'].sort());
	assert.equal(summary.namedPassThroughFunctions >= 1, true);
	assert.equal(summary.localNamedCalls >= 1, true);
	const kinds = summary.inlineCandidates.map((candidate) => candidate.kind).sort();
	assert.ok(kinds.includes('transparent-forwarder'));
	assert.ok(kinds.includes('callback-proxy'));
	const proxy = summary.inlineCandidates.find((candidate) => candidate.kind === 'callback-proxy');
	assert.equal(proxy?.name, 'onReady');
	assert.equal(proxy?.forwardsTo, 'notify');
	const rows = indirectionFindings('probe.ts', source);
	assert.ok(rows.some((row) => row.rule === 'Q1' && row.location.includes('name=onReady')));
	assert.ok(rows.some((row) => row.rule === 'Q3' && row.location.includes('name=internalShim')));
});

test('complexity: Q3 skips type predicates and constructed callees; Q4 skips earned names', () => {
	const source = `
const isRuleList = (value: unknown): value is ReadonlyArray<string> => Array.isArray(value);
export const check = (value: unknown) => isRuleList(value);
const decodeRow = (input: unknown): Row => Schema.decodeUnknownSync(Row)(input);
export const read = (input: unknown) => decodeRow(input);
const escapeLikePattern = (value: string) => value.replace(/[%_\\\\]/g, '\\\\$&');
export const like = (value: string) => escapeLikePattern(value);
const label = (name: string) => name.trim();
export const show = (name: string) => label(name);
`;
	const rows = indirectionFindings('probe.ts', source);
	assert.equal(
		rows.some((row) => row.location.includes('name=isRuleList')),
		false
	);
	assert.equal(
		rows.some((row) => row.location.includes('name=decodeRow')),
		false
	);
	assert.equal(
		rows.some((row) => row.location.includes('name=escapeLikePattern')),
		false
	);
	assert.ok(rows.some((row) => row.rule === 'Q4' && row.location.includes('name=label')));
});

// --- entities -------------------------------------------------------------------------------

test('entities: pathways require forty structural tokens and preserve literal text', () => {
	const small = pathwayHash('const tiny = a + b;');
	assert.equal(small, undefined);
	const template = (seed: string): string =>
		`const big = first(a, ${seed}); const more = second(big, '${seed}'); const extra = blend(more, ${seed}, 'z'); const last = third(extra, [1, 2, 3]);`;
	const left = pathwayHash(template(1));
	const right = pathwayHash(template(2));
	const other = pathwayHash(`const big = fourth(a, 1); const more = fifth(big, 'x', extraBit); const extra = merge(more, 1, 'z'); const last = sixth(extra, [1, 2, 3], { deep: true });`);
	assert.ok(left && right && other);
	assert.notEqual(left.hash, right.hash);
	assert.equal(left.tokens, right.tokens);
	assert.deepEqual(left.shingles, right.shingles);
	assert.notDeepEqual(left.shingles, other?.shingles);
});

test('entities: shingle similarity merges sorted lists', () => {
	const shared = ['a', 'b', 'c', 'd'];
	assert.equal(shingleSimilarity(shared, [...shared]), 1);
	assert.equal(shingleSimilarity(['a', 'b'], ['b', 'c']), 1 / 3);
	assert.equal(shingleSimilarity([], ['x']), 0);
});

function occurrenceOf(overrides: Record<string, unknown>): Record<string, unknown> {
	return {
		id: 'id',
		file: 'f',
		entity: 'name',
		kind: 'function',
		line: 1,
		concept: 'c',
		pillar: 'p',
		tokens: 100,
		cyclomatic: 1,
		nesting: 1,
		passThrough: false,
		operationSignature: null,
		...overrides
	};
}

test('entities: exact groups need cross-file agreement and classes suppress their members', () => {
	const entities = [
		occurrenceOf({ id: 'a', rootId: 'r', file: 'r/left.ts', name: 'dupe', kind: 'function', hash: 'h1', shingles: [], cyclomatic: 2 }),
		occurrenceOf({ id: 'b', rootId: 'r', file: 'r/right.ts', name: 'dupe', kind: 'function', hash: 'h1', shingles: [], cyclomatic: 2 })
	] as never;
	const evidence = pathwayEvidence(entities);
	assert.equal(evidence.exact.length, 1);
	assert.equal(evidence.exact[0]?.occurrences.length, 2);
	assert.equal(evidence.exact[0]?.hash, 'h1');
});

test('entities: labels prefer call evidence and fall back to entity words', () => {
	assert.equal(
		clusterLabel([
			occurrenceOf({ operationSignature: 'serialize:2|if:1' }) as never
		]),
		'calls: serialize'
	);
	assert.equal(clusterLabel([occurrenceOf({ entity: 'invoiceBuilder', operationSignature: null }) as never]), 'functions: builder + invoice');
	assert.equal(clusterLabel([occurrenceOf({ entity: 'run', operationSignature: null }) as never]), 'structurally duplicated pathway');
});

// --- tests-config ---------------------------------------------------------------------------

test('tests-config: commands must be able to select the candidate', () => {
	const root = scratch('doctor-testcfg');
	writeTree(root, {
		'vitest-pkg/package.json': `${JSON.stringify({ scripts: { test: 'vitest run' } })}\n`,
		'glob-pkg/package.json': `${JSON.stringify({ scripts: { 'test:unit': "node --test --test-reporter=dot 'test/**'" } })}\n`,
		'narrow-pkg/package.json': `${JSON.stringify({ scripts: { test: 'node --test test/only-this.test.ts' } })}\n`,
		'literal-pkg/package.json': `${JSON.stringify({ scripts: { check: 'skip', 'test:suite': 'node runner.mjs plain.spec.ts' } })}\n`,
		'bare-pkg/package.json': `${JSON.stringify({ name: 'bare' })}\n`,
		'broken-pkg/package.json': '{ nope\n'
	});
	try {
		const configured = (pkg: string, file: string): boolean =>
			isConfiguredTest(join(root, pkg, file), { root: join(root, pkg) });
		assert.equal(configured('vitest-pkg', 'test/anything.test.ts'), true);
		assert.equal(configured('glob-pkg', 'test/covered.test.ts'), true);
		assert.equal(configured('glob-pkg', 'src/not-a-test.ts'.replace('src/', 'test-x/')), false);
		assert.equal(configured('narrow-pkg', 'test/only-this.test.ts'), true);
		assert.equal(configured('narrow-pkg', 'test/other.test.ts'), false);
		assert.equal(configured('literal-pkg', 'plain.spec.ts'), true);
		assert.equal(configured('bare-pkg', 'test/none.test.ts'), false);
		assert.equal(configured('broken-pkg', 'test/none.test.ts'), false);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

// --- composite ------------------------------------------------------------------------------

test('composite: distributions report rounded summaries over sorted copies', () => {
	assert.deepEqual(distribution([]), { count: 0, mean: 0, stdev: 0, cv: 0, gini: 0, median: 0, p90: 0, p95: 0, max: 0 });
	const stats = distribution([4, 1, 3, 2]);
	assert.equal(stats.count, 4);
	assert.equal(stats.mean, 2.5);
	assert.equal(stats.median, 2);
	assert.equal(stats.p95, 4);
	assert.equal(stats.max, 4);
	assert.equal(stats.stdev, Math.round(Math.sqrt(1.25) * 1000) / 1000);
	assert.equal(roundedRatio(1, 0), 0);
	assert.equal(roundedRatio(1, 4, 100), 25);
});

test('composite: comparisons gate on versions and roots, then compute signed deltas', () => {
	const report = {
		schemaVersion: 8,
		analyzerVersion: 9,
		roots: [{ path: '/r', id: 'r' }],
		scorePrecision: { coupling: 40.5, modularity: 59.5, staticQuality: null },
		totals: { cyclicModules: 3, staticErrors: 1 }
	};
	const baseline = {
		schemaVersion: 8,
		analyzerVersion: 9,
		roots: [{ path: '/r', id: 'r' }],
		scorePrecision: { coupling: 39.5, modularity: 60.5, staticQuality: null },
		totals: { cyclicModules: 1, staticErrors: 0 }
	};
	const outcome = compare(report, baseline);
	assert.equal(outcome.deltas['coupling'], 1);
	assert.equal(outcome.deltas['cyclicModules'], 2);
	assert.deepEqual(outcome.regressions, ['coupling +1', 'modularity -1', 'cyclicModules +2', 'staticErrors +1']);
	assert.throws(() => compare(report, { ...baseline, schemaVersion: 7 }), /baseline analyzer\/schema does not match/);
	assert.throws(() => compare(report, { ...baseline, roots: [] }), /baseline roots do not match/);
});

// --- report ---------------------------------------------------------------------------------

test('report: paired output normalization strips one json/md extension', () => {
	assert.equal(pairedOutputRoot('/tmp/report.JSON'), '/tmp/report');
	assert.equal(pairedOutputRoot('/tmp/report.md'), '/tmp/report');
	assert.equal(pairedOutputRoot('/tmp/report'), '/tmp/report');
	assert.equal(pairedOutputRoot('/tmp/report.json.md'), '/tmp/report.json');
});

test('report: the brief renders scores, tables, and unscanned placeholders', () => {
	const brief = markdown(minimalReport());
	assert.match(brief, /^# Repository health\n/);
	assert.match(brief, /Verdict: \*\*pass\*\*/);
	assert.match(brief, /not scanned \| not scored \|/);
	assert.match(brief, /## Largest concepts/);
	assert.match(brief, /## Domain pillars/);
	assert.match(brief, /## Highest-LOC modules/);
	assert.match(brief, /Cycles: 0\. Exact duplicate groups: 0\./);
});

function minimalReport(): Parameters<typeof markdown>[0] {
	return {
		schemaVersion: 8,
		analyzerVersion: 9,
		verdict: 'pass',
		roots: [],
		totals: new Proxy(
			{},
			{
				get: (_target, property) =>
					property === 'productionCodeLoc' || property === 'testCodeLoc' ? 0 : 0
			}
		) as never,
		scores: { coupling: 1, modularity: 2, colocation: 3, testability: 4, simplicity: 5, staticQuality: null, health: null },
		scorePrecision: { coupling: 1, modularity: 2, colocation: 3, testability: 4, simplicity: 5, staticQuality: null, health: null },
		quality: null,
		distributions: {
			productionFileCodeLoc: distribution([]),
			functionCyclomatic: distribution([]),
			functionNesting: distribution([]),
			fanIn: distribution([]),
			fanOut: distribution([]),
			pillarCodeLoc: distribution([]),
			pillarCohesion: distribution([]),
			pillarComplexityDensity: distribution([]),
			pillarIndirectionDensity: distribution([])
		},
		colocation: { importEdges: emptyLocality(), importScore: 100, sameFileNamedCalls: 0 },
		concepts: [],
		pillars: [],
		services: [],
		cycles: [],
		duplicatePathways: [],
		overlappingPathways: [],
		functionalityClusters: [],
		inlineCandidates: [],
		hotspots: []
	};
}

// --- snapshot -------------------------------------------------------------------------------

test('snapshot: assembleReport publishes pairs and reports what it wrote', async () => {
	const { assembleReport } = await import('../../build/analysis/snapshot.js');
	const root = scratch('doctor-snap');
	writeTree(root, {
		'package.json': `${JSON.stringify({ name: 'tiny', scripts: { test: 'node --test' } })}\n`,
		'src/only.ts': 'export const only = 1;\n',
		'test/only.test.ts': "import { strict } from 'node:assert';\nimport { only } from '../src/only.js';\nstrict.ok(only);\n"
	});
	try {
		const out = join(scratch('doctor-snap-out'), 'report');
		const result = assembleReport({ roots: [root], format: 'both', out });
		assert.deepEqual(result.wrote, [`${out}.json`, `${out}.md`]);
		assert.equal(result.stdout, result.brief);
		assert.equal(result.verdict, 'incomplete');
		assert.equal(result.exitCode, 2);
		const published = JSON.parse(readFileSync(`${out}.json`, 'utf8')) as {
			totals: Record<string, number>;
			scorePrecision: Record<string, number | null>;
		};
		assert.equal(published.totals.files, 2);
		assert.equal(published.totals.testFiles, 1);
		assert.equal(published.scorePrecision.health, null);
		const stdoutOnly = assembleReport({ roots: [root], format: 'json' });
		assert.equal(stdoutOnly.wrote.length, 0);
		assert.match(stdoutOnly.stdout, /\n$/);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});
