import { Context, Effect, Layer, Schema } from 'effect';
import type { WorkspaceDefinition } from '../authoring/workspace-schema.js';
import { buildManifest, type ManifestInput } from '../manifest/manifest.js';
import { buildSchemaPlan, type SchemaPlan } from './schema-plan.js';

/** Carries discovery error through the typed compiler failure channel without losing diagnostic context. */
export class DiscoveryError extends Schema.TaggedError<DiscoveryError>()(
	'Bolt.Compiler.DiscoveryError',
	{
		message: Schema.NonEmptyString
	}
) {
	readonly category = 'workspace-discovery' as const;
	readonly retryable = false;
	readonly phase = 'discover' as const;
}

/** Owns deterministic workspace discovery and its generated public name unions. */
const CompilerValues = {
	discover: (
		candidates: ReadonlyArray<WorkspaceDefinition>
	): WorkspaceDefinition | DiscoveryError => {
		if (candidates.length === 0)
			return new DiscoveryError({ message: 'No Bolt workspace declaration was found' });
		if (candidates.length > 1)
			return new DiscoveryError({ message: 'Multiple Bolt workspace declarations were found' });
		const workspace = candidates[0];
		return workspace === undefined
			? new DiscoveryError({ message: 'Workspace discovery failed' })
			: workspace;
	},
	generateTypes: (workspace: WorkspaceDefinition): string => {
		const collectionNames = workspace.collections.map(({ name }) => JSON.stringify(name)).sort();
		const appNames = workspace.apps.map(({ name }) => JSON.stringify(name)).sort();
		return [
			'// Generated by Bolt. Do not edit.',
			`export type CollectionName = ${collectionNames.length === 0 ? 'never' : collectionNames.join(' | ')};`,
			`export type AppName = ${appNames.length === 0 ? 'never' : appNames.join(' | ')};`,
			''
		].join('\n');
	}
};
export const discoverWorkspace = CompilerValues.discover;
export const generateWorkspaceTypes = CompilerValues.generateTypes;

/** Carries compilation error through the typed compiler failure channel without losing diagnostic context. */
export class CompilationError extends Schema.TaggedError<CompilationError>()(
	'Bolt.Compiler.CompilationError',
	{
		message: Schema.NonEmptyString
	}
) {
	readonly category = 'workspace-compilation' as const;
	readonly retryable = false;
	readonly phase = 'compile' as const;
}

export type Compilation = Readonly<{
	readonly workspace: WorkspaceDefinition;
	readonly manifest: ReturnType<typeof buildManifest>;
	readonly schemaPlan: SchemaPlan;
	readonly generatedTypes: string;
}>;

export type Interface = Readonly<{
	readonly discover: (
		candidates: ReadonlyArray<WorkspaceDefinition>
	) => Effect.Effect<WorkspaceDefinition, DiscoveryError>;
	readonly compile: (
		workspace: WorkspaceDefinition,
		input: ManifestInput
	) => Effect.Effect<Compilation, CompilationError>;
	readonly check: (workspace: WorkspaceDefinition) => Effect.Effect<void, CompilationError>;
	readonly buildManifest: typeof buildManifest;
	readonly buildSchemaPlan: typeof buildSchemaPlan;
}>;

/** Identifies the compiler service in Effect's context so dependency wiring remains explicit and type checked. */
export const Service = Context.Service<Interface>('@norbital-ai/bolt/Compiler');

const checkWorkspace = Effect.fn('Compiler.check')(function* (workspace: WorkspaceDefinition) {
	const names = workspace.collections.map(({ name }) => name);
	if (new Set(names).size !== names.length) {
		return yield* new CompilationError({ message: 'Collection names must be unique' });
	}
	const appNames = workspace.apps.map(({ name }) => name);
	if (new Set(appNames).size !== appNames.length) {
		return yield* new CompilationError({ message: 'Application names must be unique' });
	}
});

export const layer = Layer.succeed(
	Service,
	Service.of({
		discover: Effect.fn('Compiler.discover')(function* (candidates) {
			const found = discoverWorkspace(candidates);
			if (found instanceof DiscoveryError) return yield* found;
			return found;
		}),
		compile: Effect.fn('Compiler.compile')(function* (workspace, input) {
			yield* checkWorkspace(workspace);
			return {
				workspace,
				manifest: buildManifest(workspace, input),
				schemaPlan: buildSchemaPlan(workspace),
				generatedTypes: generateWorkspaceTypes(workspace)
			};
		}),
		check: checkWorkspace,
		buildManifest,
		buildSchemaPlan
	})
);

export * as Compiler from './compiler.js';
