// repository-health:allow SEM_PARALLEL -- compiler is the build-time discover/types phase;
// runtime/workspace.ts is the runtime lookup layer. They share nothing but the WorkspaceDefinition
// input, so the pair is two phases of one contract, not one responsibility twice.
import { Schema } from 'effect';
import type { WorkspaceDefinition } from '../authoring/workspace-schema.js';

/**
 * Every exact name an application capability may grant.
 *
 * Runtime access treats a path prefix as a group grant: `hr_controller` reaches
 * `hr_controller/leave` and every other app below that directory. Generated authoring types must
 * therefore include the same prefixes, while remaining a closed union that rejects misspellings.
 */
export const appCapabilityNames = (appNames: ReadonlyArray<string>): ReadonlyArray<string> =>
	[
		...new Set(
			appNames.flatMap((name) =>
				name.split('/').map((_, index, parts) => parts.slice(0, index + 1).join('/'))
			)
		)
	]
		.filter((name) => name.length > 0)
		.toSorted();

/** Carries discovery error through the typed compiler failure channel without losing diagnostic context. */
class DiscoveryError extends Schema.TaggedError<DiscoveryError>()('Bolt.Compiler.DiscoveryError', {
	message: Schema.NonEmptyString
}) {
	readonly category = 'workspace-discovery' as const;
	readonly retryable = false;
	readonly phase = 'discover' as const;
}

/** Owns deterministic workspace discovery and its generated public name unions. */
const CompilerValues = {
	discover: (
		candidates: ReadonlyArray<WorkspaceDefinition>
	): WorkspaceDefinition | DiscoveryError => {
		if (candidates.length === 0)
			return new DiscoveryError({ message: 'No Bolt workspace declaration was found' });
		if (candidates.length > 1)
			return new DiscoveryError({ message: 'Multiple Bolt workspace declarations were found' });
		const workspace = candidates[0];
		return workspace === undefined
			? new DiscoveryError({ message: 'Workspace discovery failed' })
			: workspace;
	},
	generateTypes: (workspace: WorkspaceDefinition): string => {
		const collectionNames = workspace.collections.map(({ name }) => JSON.stringify(name)).sort();
		const appNames = appCapabilityNames(workspace.apps.map(({ name }) => name)).map((name) =>
			JSON.stringify(name)
		);
		return [
			'// Generated by Bolt. Do not edit.',
			`export type CollectionName = ${collectionNames.length === 0 ? 'never' : collectionNames.join(' | ')};`,
			`export type AppName = ${appNames.length === 0 ? 'never' : appNames.join(' | ')};`,
			''
		].join('\n');
	}
};
export const discoverWorkspace = CompilerValues.discover;
export const generateWorkspaceTypes = CompilerValues.generateTypes;
