/// <reference types="node" />
// The names index (§3.1, rule 8): `.norbital/names.ts`, the only generated code. Each path-derived name maps to
// `typeof import('<path>').default`, so content never goes stale; only the integration direction is a literal (P14).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Discovered, Role } from './discover.ts';
import { type Manifest, spec } from './load.ts';

/** `Names` part → the role it indexes; `one` parts are the singleton file's own type. */
const PARTS: { part: string; role: Role; one?: true }[] = [
	{ part: 'apps', role: 'app' }, { part: 'automations', role: 'automation' }, { part: 'channels', role: 'channel' },
	{ part: 'collections', role: 'collection' }, { part: 'connections', role: 'connection' },
	{ part: 'customFields', role: 'custom_field' }, { part: 'envoys', role: 'envoy' }, { part: 'mcp', role: 'mcp' },
	{ part: 'locales', role: 'locale' }, { part: 'messages', role: 'messages', one: true }, { part: 'models', role: 'model' },
	{ part: 'policies', role: 'policy' }, { part: 'relationships', role: 'relationship', one: true },
	{ part: 'teams', role: 'team', one: true }, { part: 'workspace', role: 'workspace', one: true },
];

const key = JSON.stringify;
const typeOf = (f: Discovered) => `typeof import(${key(`../${f.path}`)}).default`;
const record = (entries: [string, string][]) => `{ ${entries.sort(([a], [b]) => (a < b ? -1 : 1)).map(([k, v]) => `${key(k)}: ${v}`).join('; ')} }`;

/**
 * The tools a host advertises (rule 58): the render facility's browser and a host's workbench authoring.
 * ponytail: one declared list for every host; read the host port's manifest when hosts advertise different tools.
 */
const HOST_TOOLS = ['browser_act', 'browser_evaluate', 'browser_navigate', 'browser_screenshot', 'browser_snapshot',
	'sandbox_run', 'workspace_review', 'workspace_validate', 'workspace_write'] as const;

/** The text of `.norbital/names.ts`. `bolt` is the module the index augments, as seen from `.norbital/`. */
export function namesIndex(files: readonly Discovered[], manifest: Manifest, bolt = '@norbital-ai/bolt'): string {
	const lines = new Map<string, string>();
	for (const { part, role, one } of PARTS) {
		const of = files.filter((f) => f.role === role);
		if (of.length > 0) lines.set(part, one ? typeOf(of[0]!) : record(of.map((f) => [f.name, typeOf(f)])));
	}
	const directions = Object.entries(manifest.integration).flatMap(([c, i]): [string, string][] => {
		const d = spec(i).direction;
		return d === 'one_way' || d === 'two_way' ? [[c, key(d)]] : [];
	});
	if (directions.length > 0) lines.set('integrations', record(directions));
	// pages: app → union of its page names; groups: group → union of its child app and group folder names.
	const children = (parts: Role[], of: string, name: (f: Discovered) => string) =>
		files.filter((f) => parts.includes(f.role) && f.name.slice(0, Math.max(0, f.name.lastIndexOf('/'))) === of).map((f) => key(name(f))).sort().join(' | ') || 'never';
	const leaf = (f: Discovered) => f.name.slice(f.name.lastIndexOf('/') + 1);
	const apps = files.filter((f) => f.role === 'app');
	if (files.some((f) => f.role === 'page')) lines.set('pages', record(apps.map((a) => [a.name, children(['page'], a.name, leaf)])));
	const groups = files.filter((f) => f.role === 'group');
	if (groups.length > 0) lines.set('groups', record(groups.map((g) => [g.name, children(['app', 'group'], g.name, leaf)])));
	const skills = files.filter((f) => f.role === 'skill');
	if (skills.length > 0) lines.set('skills', record(skills.map((f) => [f.name, 'true'])));
	lines.set('hostTools', record(HOST_TOOLS.map((t) => [t, 'true'])));

	return `// Generated by bolt from the workspace paths: the names index (rule 8). Never edited.
import type { Check, Verify } from ${key(bolt)};

declare module ${key(bolt)} {
	interface Names {
${[...lines].sort(([a], [b]) => (a < b ? -1 : 1)).map(([part, type]) => `\t\t${part}: ${type};`).join('\n')}
	}
}

// Every cross-file declaration error of the workspace fails here (§3.3.9, X-12).
export const __verify: Check<Verify> = true;
`;
}

/**
 * The built-in layer's index, `src/system/index.ts`: bolt's own models, relationships and collections, discovered under
 * `src/system` exactly as a workspace's are (`discover(root, 'system')`). Each declaration is imported once; its names are
 * typed as a workspace's names index types them (`typeof import(<path>).default`), and the literals are the layer's
 * manifest, which the schema plan, the catalogue and the names types merge into every workspace. A test compares the file
 * with this text, so the layer's paths are its only source.
 */
export function systemIndex(files: readonly Discovered[]): string {
	const rel = (f: Discovered) => `./${f.path.slice('src/system/'.length)}`;
	const of = (role: Role) => files.filter((f) => f.role === role).sort((a, b) => (a.name < b.name ? -1 : 1));
	const models = of('model'), collections = of('collection'), relationships = of('relationship')[0];
	const imports = [...models.map((f) => `import m_${f.name} from ${key(rel(f))};`),
		...(relationships === undefined ? [] : [`import relationships from ${key(rel(relationships))};`]),
		...collections.map((f) => `import c_${f.name} from ${key(rel(f))};`)];
	const rows = (list: readonly Discovered[], v: (f: Discovered) => string) => list.map((f) => `\t\t${f.name}: ${v(f)};`).join('\n');
	const values = (list: readonly Discovered[], v: (f: Discovered) => string) => list.map((f) => `\t\t${f.name}: ${v(f)},`).join('\n');
	return `// Generated by bolt from the paths under src/system (\`systemIndex\`, compiler/names.ts): the built-in layer, compiled as
// a workspace is. Never edited; tests/system-layer.test.ts fails when it drifts from the paths.
import type { CollectionSpec } from '../decl/collection.ts';
import type { ModelSpec } from '../decl/model.ts';
import type { RelationshipSpec } from '../decl/names.ts';
${imports.join('\n')}

/** The layer's names index: each name → its declaration's type, as a workspace's \`.norbital/names.ts\` maps one. */
export type SystemNames = {
	models: {
${rows(models, (f) => `typeof m_${f.name}`)}
	};
	relationships: ${relationships === undefined ? '{}' : 'typeof relationships'};
	collections: {
${rows(collections, (f) => `typeof c_${f.name}`)}
	};
};
/** The layer's manifest: merged into every workspace's schema plan, catalogue and names. */
export const SYSTEM: {
	models: { readonly [model: string]: ModelSpec };
	relationships: { readonly [key: string]: RelationshipSpec };
	collections: { readonly [collection: string]: CollectionSpec };
} = {
	models: {
${values(models, (f) => `m_${f.name}`)}
	},
	relationships: ${relationships === undefined ? '{}' : 'relationships'},
	collections: {
${values(collections, (f) => `c_${f.name}.spec`)}
	},
};
`;
}

/** Writes `.norbital/names.ts` only when its text changes (rule 8); returns whether it wrote. */
export function writeNames(root: string, text: string): boolean {
	const path = join(root, '.norbital', 'names.ts');
	if (existsSync(path) && readFileSync(path, 'utf8') === text) return false;
	mkdirSync(join(root, '.norbital'), { recursive: true });
	writeFileSync(path, text);
	return true;
}

/**
 * The generated type setup (§3.1): the workspace `tsconfig.json` extends `.norbital/tsconfig.json`, which carries the
 * compiler options and includes the names index and `bolt.d.ts`, the `$bolt` alias of `@norbital-ai/bolt/client` and `?bytes` imports. A
 * workspace writes no declaration of its own. Each file is written only when its text changes.
 */
export const TSCONFIG = `${JSON.stringify({
	compilerOptions: { target: 'ES2024', module: 'ESNext', moduleResolution: 'bundler', strict: true, exactOptionalPropertyTypes: true,
		noUncheckedIndexedAccess: true, verbatimModuleSyntax: true, allowImportingTsExtensions: true, resolveJsonModule: true, skipLibCheck: true, noEmit: true },
	include: ['../src/**/*.ts', '../src/**/*.svelte', '../seed/**/*.ts', '../tests/**/*.ts', 'names.ts', 'bolt.d.ts'],
}, null, '\t')}\n`;
export const BOLT_DTS = `// Generated by bolt: \`$bolt\` is the booted shell client (§3.5). Never edited.
declare module '$bolt' {
	export { bolt } from '@norbital-ai/bolt/client';
}
// a server asset (§5.8): the file's bytes, read synchronously in the isolate
declare module '*?bytes' {
	const bytes: Uint8Array;
	export default bytes;
}
`;
export function writeTypeSetup(root: string): void {
	const dir = join(root, '.norbital');
	mkdirSync(dir, { recursive: true });
	for (const [file, text] of [['tsconfig.json', TSCONFIG], ['bolt.d.ts', BOLT_DTS]] as const)
		if (!existsSync(join(dir, file)) || readFileSync(join(dir, file), 'utf8') !== text) writeFileSync(join(dir, file), text);
}
