import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
	existsSync,
	mkdtempSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	realpathSync,
	rmSync,
	writeFileSync
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, sep } from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const analyzer = fileURLToPath(new URL('./analyze.mjs', import.meta.url));
// The shell entrypoints are gone with the legacy detector; the CLI is the only way in now.
const assessor = fileURLToPath(new URL('../../build/cli.js', import.meta.url));
// Mirrors the scanner's own discovery. Kept in step with `SCANNER_SOURCE_EXTENSIONS`: a receipt
// built from a different set reports as stale, which is what this fixture is for.
const sourceExtensions = ['.ts', '.tsx', '.mts', '.cts', '.js', '.jsx', '.mjs', '.cjs', '.svelte'];

function write(path, content) {
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, content);
}

const generatedHeader = /^\s*(?:\/\/|\/\*)[^\n]{0,120}(?:@generated|generated by|do not edit)/i;

function scannerExcluded(root, file) {
	return (
		/\.d\.(?:ts|mts|cts)$/.test(file) ||
		/(?:^|\/)[^/]+\.(?:generated|gen)(?:\.svelte)?\.(?:[cm]?[jt]sx?|svelte)$/.test(file) ||
		/(^|\/)(node_modules|\.yalc|build|dist|coverage|generated|\.generated|\.svelte-kit(?:-e2e)?|\.tmp|\.data|\.agents|\.opencode)(\/|$)/.test(
			file
		) ||
		/(^|\/)(test|tests|e2e|__tests__)(\/|$)/.test(file) ||
		/\.(test|spec)\.[^.]+$/.test(file) ||
		generatedHeader.test(readFileSync(join(root, file), 'utf8').slice(0, 500))
	);
}

function receiptInventory(root) {
	const sources = [];
	const visit = (directory) => {
		for (const entry of readdirSync(directory, { withFileTypes: true })) {
			const path = join(directory, entry.name);
			if (entry.isDirectory()) visit(path);
			else if (entry.isFile()) {
				const local = relative(root, path).split(sep).join('/');
				if (
					sourceExtensions.some((extension) => entry.name.endsWith(extension)) &&
					!scannerExcluded(root, local)
				)
					sources.push(local);
			}
		}
	};
	visit(root);
	sources.sort();
	const inputs = new Set(sources);
	for (const file of sources) {
		let directory = dirname(join(root, file));
		while (directory === root || directory.startsWith(`${root}${sep}`)) {
			for (const name of ['package.json', 'tsconfig.json', 'jsconfig.json']) {
				const candidate = join(directory, name);
				if (existsSync(candidate)) inputs.add(relative(root, candidate).split(sep).join('/'));
			}
			if (directory === root) break;
			directory = dirname(directory);
		}
	}
	const digest = createHash('sha256');
	for (const file of [...inputs].sort()) {
		const fileHash = createHash('sha256')
			.update(readFileSync(join(root, file)))
			.digest('hex');
		digest.update(`${file}\0${fileHash}\n`);
	}
	return { files: sources.length, digest: `sha256:${digest.digest('hex')}` };
}

function makeReceipt(root, rows = [], { typeAware = true } = {}) {
	const directory = join(root, '.norbital/diagnosis');
	const catalogue = join(directory, 'findings.tsv');
	const content = rows.join('\n') + (rows.length ? '\n' : '');
	write(catalogue, content);
	const inventory = receiptInventory(root);
	const counts = {
		error: 0,
		warning: 0,
		hint: 0,
		total: rows.length,
		principles: {
			simplicity: 0,
			straightforwardness: 0,
			modularity: 0,
			testability: 0,
			efficiency: 0,
			typeSafety: 0,
			colocation: 0,
			noBloat: 0
		}
	};
	for (const row of rows) {
		const [severity, , , , , encoded] = row.split('\t');
		counts[severity] += 1;
		for (const principle of encoded.split(',')) {
			const key =
				principle === 'no-bloat'
					? 'noBloat'
					: principle === 'type-safety'
						? 'typeSafety'
						: principle;
			counts.principles[key] += 1;
		}
	}
	const receipt = join(directory, 'receipt.json');
	write(
		receipt,
		JSON.stringify({
			schemaVersion: 5,
			kind: 'repository-health-static-receipt',
			scannerVersion: 31,
			root: realpathSync(root),
			scope: 'all',
			includeTests: false,
			tiers: { syntactic: true, graph: true, typeAware },
			files: inventory.files,
			sourceInventoryDigest: inventory.digest,
			ruleSetDigest: `sha256:${'1'.repeat(64)}`,
			catalogueDigest: `sha256:${createHash('sha256').update(content).digest('hex')}`,
			counts,
			findings: 'findings.tsv',
			complete: true
		})
	);
	return receipt;
}

function temporary(name) {
	return mkdtempSync(join(tmpdir(), `repository-health-${name}-`));
}

function fixture() {
	const root = temporary('main');
	write(join(root, 'package.json'), JSON.stringify({ name: 'fixture-root', private: true }));
	write(
		join(root, 'packages/a/package.json'),
		JSON.stringify({
			name: '@fixture/a',
			scripts: { test: 'node --test tests/*.test.ts' },
			imports: { '#lib/*': './src/*' },
			exports: {
				'.': { default: './build/index.js' },
				'./feature': { default: './build/feature.js' }
			}
		})
	);
	write(
		join(root, 'packages/a/tsconfig.json'),
		JSON.stringify({ compilerOptions: { baseUrl: 'src', paths: { '$lib/*': ['*'] } } })
	);
	write(
		join(root, 'packages/a/src/index.ts'),
		"// excluded comment\nimport { a } from '#lib/a';\nimport { b } from '$lib/b';\nexport const total = a + b;\n"
	);
	write(
		join(root, 'packages/a/src/a.ts'),
		"/* excluded block\n * line two\n */\nimport { b } from './b';\nexport const a = b + 1;\n"
	);
	write(join(root, 'packages/a/src/b.ts'), "import { a } from './a';\nexport const b = a + 1;\n");
	write(join(root, 'packages/a/src/feature.ts'), 'export const feature = 1;\n');
	write(
		join(root, 'packages/a/src/duplicate-one.ts'),
		`export function calculate(values: number[]) {
	let total = 0;
	for (const value of values) {
		if (value > 0) total += value * 2;
		else if (value < 0) total -= Math.abs(value);
		else total += 1;
	}
	return total / Math.max(values.length, 1);
}
`
	);
	write(
		join(root, 'packages/a/src/service.ts'),
		"import { Context, Effect } from 'effect';\nexport class FixtureService extends Effect.Service<FixtureService>()('FixtureService', {}) {}\nexport const ContextService = Context.Service<{}>('ContextService');\n"
	);
	write(
		join(root, 'packages/a/tests/index.test.ts'),
		"import { total } from '../src/index';\nvoid total;\n"
	);
	write(
		join(root, 'packages/b/package.json'),
		JSON.stringify({ name: '@fixture/b', exports: { '.': './build/index.js' } })
	);
	write(
		join(root, 'packages/b/src/index.ts'),
		"import { feature } from '@fixture/a/feature';\nexport const other = feature;\n"
	);
	write(
		join(root, 'packages/b/src/duplicate-two.ts'),
		`export function summarize(entries: number[]) {
	let result = 0;
	for (const entry of entries) {
		if (entry > 0) result += entry * 2;
		else if (entry < 0) result -= Math.abs(entry);
		else result += 1;
	}
	return result / Math.max(entries.length, 1);
}
`
	);
	const receipt = makeReceipt(root, [
		'error\thigh\tEFF1\tnative try/catch\tpackages/a/src/a.ts:4: try {}\tsimplicity,testability',
		'warning\thigh\tQ3\tone-off function\tpackages/a/src/feature.ts:1: feature\tno-bloat'
	]);
	return { root, receipt };
}

function run(roots, receipts = [], extra = []) {
	const args = [analyzer];
	for (const root of roots) args.push('--root', root);
	for (const receipt of receipts) args.push('--receipt', receipt);
	args.push('--format', 'json', ...extra);
	return spawnSync(process.execPath, args, { encoding: 'utf8' });
}

test('discovers a non-git tree without requiring ripgrep', (context) => {
	const root = temporary('portable-discovery');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'portable-discovery' }));
	write(join(root, 'src/index.ts'), 'export const value = 1;\n');
	const result = spawnSync(
		process.execPath,
		[analyzer, '--root', root, '--overlap-only', '--format', 'json'],
		{ encoding: 'utf8', env: { ...process.env, PATH: '' } }
	);
	assert.equal(result.status, 0, result.stderr);
	assert.equal(JSON.parse(result.stdout).totals.productionFiles, 1);
});

test('is deterministic and resolves baseUrl aliases, exports, cycles, configured tests, services, and principles', (context) => {
	const { root, receipt } = fixture();
	context.after(() => rmSync(root, { recursive: true, force: true }));
	const first = run([root], [receipt]);
	const second = run([root], [receipt]);
	assert.equal(first.status, 1, first.stderr);
	assert.equal(first.stderr, '');
	assert.equal(first.stdout, second.stdout);
	const report = JSON.parse(first.stdout);
	assert.equal(report.schemaVersion, 8);
	assert.equal(report.analyzerVersion, 9);
	assert.equal(report.verdict, 'fail');
	assert.equal(report.totals.productionFiles, 8);
	assert.equal(report.totals.testFiles, 1);
	assert.equal(report.totals.unconfiguredTestFiles, 0);
	assert.equal(report.totals.internalImportEdges, 5);
	assert.equal(report.totals.unresolvedInternalImports, 0);
	assert.equal(report.totals.crossConceptEdges, 1);
	assert.equal(report.totals.cyclicModules, 2);
	assert.equal(report.totals.cycleGroups, 1);
	assert.equal(report.totals.duplicatePathwayGroups, 1);
	assert.equal(typeof report.totals.overlappingPathwayPairs, 'number');
	assert.equal(report.totals.services, 2);
	assert.equal(report.totals.testReachedProductionModules, 3);
	assert.equal(report.totals.commentLoc, 4);
	assert.deepEqual(report.quality.totals, { error: 1, warning: 1, hint: 0 });
	assert.deepEqual(
		report.quality.byPrinciple.map(({ name, count }) => [name, count]),
		[
			['simplicity', 1],
			['straightforwardness', 0],
			['modularity', 0],
			['testability', 1],
			['efficiency', 0],
			['type-safety', 0],
			['colocation', 0],
			['no-bloat', 1]
		]
	);
	assert.equal(typeof report.quality.byPrinciple[0].perThousandProductionLoc, 'number');
});

test('overlap-only mode quickly separates exact and high-confidence near duplicates', (context) => {
	const root = temporary('overlap');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'overlap' }));
	const owner = `export function calculate(values: number[]) {
	const normalized = values.slice();
	let total = 0;
	for (const value of normalized) {
		if (value > 10) total += Math.round(Math.abs(value) * 2);
		else if (value > 0) total += Math.round(value);
		else if (value < 0) total -= Math.round(Math.abs(value));
		else total += 1;
	}
	return Math.max(total, 0) / Math.max(normalized.length, 1);
}
`;
	const copy = owner.replace('calculate', 'summarize');
	const overlap = copy.replace('let total = 0;', 'let total = 0;\n\tvoid normalized;');
	write(join(root, 'src/owner.ts'), owner);
	write(join(root, 'src/copy.ts'), copy);
	write(join(root, 'src/overlap.ts'), overlap);
	write(
		join(root, 'src/unrelated.ts'),
		overlap.replaceAll('Math.round', 'Number.parseInt').replace('summarize', 'parseValues')
	);
	const result = run([root], [], ['--overlap-only']);
	assert.equal(result.status, 1, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.mode, 'overlap-only');
	assert.equal(report.totals.productionFiles, 4);
	assert.equal(report.totals.duplicatePathwayGroups, 1);
	assert.equal(report.totals.overlappingPathwayPairs, 2, JSON.stringify(report, null, 2));
	assert.equal(report.totals.functionalityClusters, 1);
	assert.equal(report.totals.clusteredEntityOccurrences, 3);
	assert.equal(report.functionalityClusters[0].members.length, 3);
	assert.equal(report.functionalityClusters[0].exactRelationships, 1);
	assert.equal(report.functionalityClusters[0].overlapRelationships, 2);
	assert.equal(report.functionalityClusters[0].overlapDensity, 1);
	assert.equal(report.functionalityClusters[0].pillars.length, 1);
	assert.equal(report.functionalityClusters[0].crossPillar, false);
	assert.equal(report.functionalityClusters[0].colocation.samePillarShare, 1);
	assert.equal(typeof report.functionalityClusters[0].complexity.excessCyclomatic, 'number');
	assert.equal(typeof report.functionalityClusters[0].indirection.passThroughMembers, 'number');
	assert.match(report.functionalityClusters[0].label, /^calls: /);
	assert.equal(typeof report.functionalityClusters[0].complexity.cyclomatic.p95, 'number');
	assert.ok(report.overlappingPathways.every(({ similarity }) => similarity >= 0.88));
	assert.equal(
		report.overlappingPathways.some(({ left, right }) =>
			[left.file, right.file].some((file) => file.endsWith('unrelated.ts'))
		),
		false
	);
});

test('duplicate evidence is entity-level and never compares repeated inline statements', (context) => {
	const root = temporary('entity-overlap');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'entity-overlap' }));
	const body = `{
	let total = 0;
	for (const value of values) {
		if (value > 10) total += Math.round(Math.abs(value) * 2);
		else if (value > 0) total += Math.round(value);
		else if (value < 0) total -= Math.round(Math.abs(value));
		else total += 1;
	}
	return Math.max(total, 0) / Math.max(values.length, 1);
}`;
	const constructorBody = `{
	let total = 0;
	for (const value of values) {
		total += Math.round(Math.abs(value));
	}
	this.total = Math.max(total, 0);
}`;
	write(join(root, 'src/class-a.ts'), `export class First { calculate(values: number[]) ${body} }`);
	write(
		join(root, 'src/class-b.ts'),
		`export class Second { calculate(values: number[]) ${body} }`
	);
	write(
		join(root, 'src/method-a.ts'),
		`export class MethodA { extraA = true; calculate(values: number[]) ${body} }`
	);
	write(
		join(root, 'src/method-b.ts'),
		`export class MethodB { extraB = true; another = 1; calculate(values: number[]) ${body} }`
	);
	write(
		join(root, 'src/constructor-a.ts'),
		`export class ConstructorA { total = 0; extraA = true; constructor(values: number[]) ${constructorBody} }`
	);
	write(
		join(root, 'src/constructor-b.ts'),
		`export class ConstructorB { total = 0; extraB = true; another = 1; constructor(values: number[]) ${constructorBody} }`
	);
	for (const [name, values] of [
		['inline-a', '1, 2, 3'],
		['inline-b', '4, 5, 6']
	])
		write(
			join(root, `src/${name}.ts`),
			`export const rows = [${values}].map((value) => {
				const doubled = value * 2;
				const bounded = Math.max(doubled, 0);
				return Math.round(bounded);
			});`
		);
	const result = run([root], [], ['--overlap-only']);
	assert.equal(result.status, 1, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.totals.duplicatePathwayGroups, 3, JSON.stringify(report, null, 2));
	assert.deepEqual(report.duplicatePathways.map(({ kind }) => kind).sort(), [
		'callable',
		'callable',
		'class'
	]);
	const occurrences = report.duplicatePathways.flatMap(({ occurrences }) => occurrences);
	assert.equal(occurrences.filter(({ kind }) => kind === 'class').length, 2);
	assert.equal(occurrences.filter(({ kind }) => kind === 'method').length, 4);
	assert.equal(occurrences.filter(({ entity }) => /\.constructor$/.test(entity)).length, 2);
	assert.equal(
		occurrences.some(({ file }) => file.includes('inline-a') || file.includes('inline-b')),
		false
	);
	assert.equal(
		occurrences.some(({ file, kind }) => /class-[ab]\.ts$/.test(file) && kind === 'method'),
		false
	);
});

test('exact duplicate hashes preserve behavior-changing literal values', (context) => {
	const root = temporary('literal-sensitive-overlap');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'literal-sensitive-overlap' }));
	write(
		join(root, 'src/status.ts'),
		`export function statusLabel(value: string) {
			switch (value) {
				case 'draft': return 'Draft item';
				case 'ready': return 'Ready item';
				case 'closed': return 'Closed item';
				case 'archived': return 'Archived item';
				default: return 'Unknown item';
			}
		}`
	);
	write(
		join(root, 'src/command.ts'),
		`export function commandLabel(value: string) {
			switch (value) {
				case 'start': return 'Start command';
				case 'pause': return 'Pause command';
				case 'finish': return 'Finish command';
				case 'cancel': return 'Cancel command';
				default: return 'Unknown command';
			}
		}`
	);
	const result = run([root], [], ['--overlap-only']);
	assert.notEqual(result.status, 2, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.duplicatePathways.length, 0, JSON.stringify(report, null, 2));
});

test('pillar clusters measure complexity, cohesion, colocation, and bounded inline opportunities', (context) => {
	const root = temporary('pillars');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'pillars' }));
	write(
		join(root, 'src/orders/index.ts'),
		`import { result } from './helper.js';
import { child } from './child/thing.js';
import { billing } from '../billing/index.js';
export const order = result + child + billing;
`
	);
	write(
		join(root, 'src/orders/helper.ts'),
		`const normalize = (value: string) => value.trim();
function forward(value: string) { return normalize(value); }
export const result = forward('order');
const notify = (value: string) => value;
function notifyProxy(value: string) { return notify(value); }
const noticed = notifyProxy('notice');

export function publicBoundary(value: string) { return value.trim(); }
const selected = publicBoundary('public');

function branch(value: number) {
	if (value > 0) return value;
	return 0;
}
const branched = branch(1);
const callback = (value: number) => value + 1;
export const retained = [noticed, selected, branched, [1].map(callback)];
`
	);
	write(join(root, 'src/orders/child/thing.ts'), 'export const child = 1;\n');
	write(join(root, 'src/billing/index.ts'), 'export const billing = 2;\n');
	const receipt = makeReceipt(root, [
		'warning\thigh\tQ3\tprivate forwarder\tsrc/orders/helper.ts:2: function forward [name=forward kind=transparent-forwarder references=1 lines=1]\tsimplicity,colocation,no-bloat',
		'warning\thigh\tQ1\tcallback proxy\tsrc/orders/helper.ts:5: function notifyProxy [name=notifyProxy]\tsimplicity,colocation,no-bloat',
		'hint\tmedium\tQ4\tprivate expression\tsrc/orders/helper.ts:1: const normalize [name=normalize kind=single-use-expression references=1 lines=1]\tsimplicity,colocation,no-bloat'
	]);
	const result = run([root], [receipt]);
	assert.equal(result.status, 1, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.schemaVersion, 8);
	assert.equal(report.totals.pillars, 2);
	assert.equal(report.totals.inlineCandidates, 3);
	assert.equal(report.totals.highConfidenceInlineCandidates, 2);
	assert.equal(report.totals.reviewInlineCandidates, 1);
	assert.equal(report.totals.transparentForwarders, 1);
	assert.equal(report.totals.callbackProxies, 1);
	assert.equal(report.totals.singleUseExpressions, 1);
	const orders = report.pillars.find(({ name }) => name === 'orders');
	assert.ok(orders);
	assert.equal(orders.files.length, 3);
	assert.equal(orders.concepts.length, 2);
	assert.equal(orders.edges.internal, 2);
	assert.equal(orders.edges.outbound, 1);
	assert.equal(orders.cohesion, 0.8);
	assert.deepEqual(orders.colocation.imports, {
		sameDirectory: 1,
		parentChild: 1,
		sameConcept: 0,
		samePillar: 0,
		samePackage: 1,
		crossPackage: 0,
		crossRoot: 0
	});
	assert.equal(orders.colocation.importScore, 75);
	assert.equal(orders.colocation.sameFileNamedCalls, 6);
	assert.deepEqual(
		orders.indirection.candidates.map(({ name, kind, confidence }) => [name, kind, confidence]),
		[
			['normalize', 'single-use-expression', 'review'],
			['forward', 'transparent-forwarder', 'high'],
			['notifyProxy', 'callback-proxy', 'high']
		]
	);
	assert.equal(orders.indirection.highConfidence, 2);
	assert.equal(orders.indirection.review, 1);
	assert.equal(orders.indirection.callbackProxies, 1);
	assert.equal(
		orders.indirection.candidates.some(({ name }) =>
			['publicBoundary', 'branch', 'callback'].includes(name)
		),
		false
	);
	assert.equal(typeof orders.complexity.excessPerThousandLoc, 'number');
	assert.equal(report.scores.colocation, 75);
});

test('functionality clusters never merge independent selected roots', (context) => {
	const parent = temporary('independent-overlap');
	context.after(() => rmSync(parent, { recursive: true, force: true }));
	const body = `export function compute(values: number[]) {
	let total = 0;
	for (const value of values) {
		if (value > 10) total += Math.round(Math.abs(value) * 2);
		else if (value > 0) total += Math.round(value);
		else if (value < 0) total -= Math.round(Math.abs(value));
		else total += 1;
	}
	return Math.max(total, 0) / Math.max(values.length, 1);
}
`;
	const roots = [join(parent, 'left'), join(parent, 'right')];
	for (const root of roots) {
		write(join(root, 'package.json'), JSON.stringify({ name: 'standalone' }));
		write(join(root, 'src/index.ts'), body);
	}
	const result = run(roots, [], ['--overlap-only']);
	assert.equal(result.status, 0, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.totals.duplicatePathwayGroups, 0);
	assert.equal(report.totals.overlappingPathwayPairs, 0);
	assert.equal(report.totals.functionalityClusters, 0);
});

test('consolidated assessment refreshes and authenticates the smell scan before health analysis', (context) => {
	const root = temporary('assessment');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(
		join(root, 'package.json'),
		JSON.stringify({ name: 'assessment', exports: './src/index.ts' })
	);
	write(join(root, 'src/index.ts'), 'export const value = 1;\n');
	const result = spawnSync(
		process.execPath,
		[assessor, 'assess', '--root', root, '--format', 'json'],
		{
			encoding: 'utf8'
		}
	);
	assert.equal(result.status, 0, `${result.stderr}\n${result.stdout}`);
	const report = JSON.parse(result.stdout);
	assert.equal(report.schemaVersion, 8);
	assert.equal(report.verdict, 'pass');
	assert.deepEqual(report.quality.totals, { error: 0, warning: 0, hint: 0 });
	assert.equal(existsSync(join(root, '.norbital/diagnosis/receipt.json')), true);
});

test('consolidated assessment normalizes an explicit extension for paired output', (context) => {
	const root = temporary('assessment-output');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(
		join(root, 'package.json'),
		JSON.stringify({ name: 'assessment-output', exports: './src/index.ts' })
	);
	write(join(root, 'src/index.ts'), 'export const value = 1;\n');
	const output = join(root, '.norbital/diagnosis/realm.json');
	const result = spawnSync(
		process.execPath,
		[assessor, 'assess', '--root', root, '--format', 'both', '--out', output],
		{ encoding: 'utf8' }
	);
	assert.equal(result.status, 0, `${result.stderr}\n${result.stdout}`);
	assert.equal(existsSync(join(root, '.norbital/diagnosis/realm.json')), true);
	assert.equal(existsSync(join(root, '.norbital/diagnosis/realm.md')), true);
	assert.equal(existsSync(join(root, '.norbital/diagnosis/realm.json.json')), false);
	assert.equal(existsSync(join(root, '.norbital/diagnosis/realm.json.md')), false);
});

test('requires an authenticated receipt and rejects stale source state', (context) => {
	const { root, receipt } = fixture();
	context.after(() => rmSync(root, { recursive: true, force: true }));
	const missing = run([root]);
	assert.equal(missing.status, 2);
	assert.equal(JSON.parse(missing.stdout).verdict, 'incomplete');
	writeFileSync(join(root, 'packages/a/src/feature.ts'), 'export const feature = 2;\n');
	const stale = run([root], [receipt]);
	assert.equal(stale.status, 2);
	assert.match(stale.stderr, /input inventory is stale/);
	const refreshed = makeReceipt(root);
	writeFileSync(
		join(root, 'packages/a/tsconfig.json'),
		JSON.stringify({ compilerOptions: { baseUrl: '.', paths: { '$lib/*': ['src/*'] } } })
	);
	const staleConfig = run([root], [refreshed]);
	assert.equal(staleConfig.status, 2);
	assert.match(staleConfig.stderr, /input inventory is stale/);
	const tampered = makeReceipt(root);
	writeFileSync(join(root, '.norbital/diagnosis/findings.tsv'), 'tampered\n');
	const staleCatalogue = run([root], [tampered]);
	assert.equal(staleCatalogue.status, 2);
	assert.match(staleCatalogue.stderr, /catalogue digest mismatch/);
});

test('records tier coverage and refuses a release gate whose type-aware tier never ran', (context) => {
	const { root } = fixture();
	context.after(() => rmSync(root, { recursive: true, force: true }));

	// A syntactic+graph scan is valid evidence and reports as such.
	const fast = makeReceipt(root, [], { typeAware: false });
	const scanned = run([root], [fast]);
	const report = JSON.parse(scanned.stdout);
	assert.equal(report.quality.coverage.tiers.typeAware, false);
	assert.deepEqual(report.quality.coverage.rootsWithoutTypeAware, [realpathSync(root)]);
	assert.notEqual(report.verdict, 'incomplete');
	assert.match(run([root], [fast], ['--format', 'markdown']).stdout, /type-aware not run/);

	// Asking for the tier and not having it is incomplete evidence, not a pass.
	const required = run([root], [fast], ['--require-type-aware']);
	assert.equal(required.status, 2);
	assert.equal(JSON.parse(required.stdout).verdict, 'incomplete');

	// The same gate is satisfied once the tier actually ran.
	const full = makeReceipt(root, [], { typeAware: true });
	const satisfied = run([root], [full], ['--require-type-aware']);
	assert.equal(JSON.parse(satisfied.stdout).quality.coverage.tiers.typeAware, true);
	assert.notEqual(JSON.parse(satisfied.stdout).verdict, 'incomplete');

	// A receipt that does not state its tiers at all is not authenticatable.
	const receiptPath = join(root, '.norbital/diagnosis/receipt.json');
	const withoutTiers = JSON.parse(readFileSync(receiptPath, 'utf8'));
	delete withoutTiers.tiers;
	writeFileSync(receiptPath, JSON.stringify(withoutTiers));
	const unstated = run([root], [receiptPath]);
	assert.equal(unstated.status, 2);
	assert.match(unstated.stderr, /fields do not match schema/);

	// So is one that claims a tier ran without saying whether it did.
	writeFileSync(
		receiptPath,
		JSON.stringify({ ...withoutTiers, tiers: { syntactic: true, graph: true } })
	);
	const malformed = run([root], [receiptPath]);
	assert.equal(malformed.status, 2);
	assert.match(malformed.stderr, /does not record tier coverage/);
});

test('resolves require, Vite query, URL worker, and self-cycle edges', (context) => {
	const root = temporary('edges');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'edges', exports: './build/index.js' }));
	write(
		join(root, 'jsconfig.json'),
		JSON.stringify({ compilerOptions: { baseUrl: 'src', paths: { '@/*': ['*'] } } })
	);
	write(join(root, 'src/alias.ts'), 'export const alias = 1;\n');
	write(join(root, 'src/required.ts'), 'export const required = 1;\n');
	write(join(root, 'src/worker.ts'), 'export const worker = 1;\n');
	write(join(root, 'src/url-worker.ts'), 'export const worker = 2;\n');
	write(
		join(root, 'src/index.ts'),
		"import './alias.js';\nrequire('./required.js');\nimport worker from './worker.ts?worker&url';\nnew Worker(new URL('./url-worker.js', import.meta.url));\nvoid worker;\nexport const index = 1;\n"
	);
	write(
		join(root, 'src/consumer.ts'),
		"import { index } from 'edges';\nimport { alias } from '@/alias';\nexport const value = index + alias;\n"
	);
	write(join(root, 'src/self.ts'), "import './self.js';\nexport const self = 1;\n");
	const result = run([root], [makeReceipt(root)]);
	assert.equal(result.status, 0, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.totals.internalImportEdges, 7);
	assert.equal(report.totals.unresolvedInternalImports, 0);
	assert.equal(report.totals.cyclicModules, 1);
	assert.equal(report.totals.cycleGroups, 1);
});

test('keeps colliding root and package names distinct and rejects overlapping roots', (context) => {
	const parent = temporary('roots');
	context.after(() => rmSync(parent, { recursive: true, force: true }));
	const left = join(parent, 'left/same');
	const right = join(parent, 'right/same');
	for (const root of [left, right]) {
		write(join(root, 'package.json'), JSON.stringify({ name: '@fixture/same' }));
		write(
			join(root, 'src/index.ts'),
			"import { value as own } from '@fixture/same';\nexport const value = own ?? 1;\n"
		);
	}
	const result = run([left, right], [makeReceipt(left), makeReceipt(right)]);
	assert.equal(result.status, 0, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(new Set(report.roots.map(({ id }) => id)).size, 2);
	assert.equal(new Set(report.concepts.map(({ concept }) => concept)).size, 2);
	assert.equal(report.totals.internalImportEdges, 2);
	assert.equal(report.totals.cyclicModules, 2);
	const overlap = run([left, join(left, 'src')]);
	assert.equal(overlap.status, 2);
	assert.match(overlap.stderr, /selected roots overlap/);
});

test('test reach excludes unconfigured tests and type-only edges', (context) => {
	const root = temporary('reach');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(
		join(root, 'package.json'),
		JSON.stringify({ name: 'reach', scripts: { test: 'node --test tests/value.test.ts' } })
	);
	write(join(root, 'src/a.ts'), "import { b } from './b.js';\nexport const a = b;\n");
	write(join(root, 'src/b.ts'), 'export const b = 1;\n');
	write(join(root, 'src/type.ts'), 'export interface OnlyType { value: string }\n');
	write(
		join(root, 'src/default.ts'),
		'export default 1;\nexport interface DefaultType { value: string }\n'
	);
	write(
		join(root, 'tests/value.test.ts'),
		"import { a } from '../src/a.js';\nimport value, { type DefaultType } from '../src/default.js';\nconst typed: DefaultType = { value: String(value) };\nvoid a;\nvoid typed;\n"
	);
	write(
		join(root, 'tests/unconfigured.spec.ts'),
		"import type { OnlyType } from '../src/type.js';\nconst value: OnlyType | null = null;\nvoid value;\n"
	);
	const result = run([root], [makeReceipt(root)]);
	assert.equal(result.status, 0, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.totals.testFiles, 1);
	assert.equal(report.totals.unconfiguredTestFiles, 1);
	assert.equal(report.totals.testReachedProductionModules, 3);
});

test('counts script comments, new extensions, generated names, and nested complexity correctly', (context) => {
	const root = temporary('syntax');
	context.after(() => rmSync(root, { recursive: true, force: true }));
	write(join(root, 'package.json'), JSON.stringify({ name: 'syntax' }));
	write(
		join(root, 'src/template.mts'),
		'export const value = `\n${(() => {\n// actual interpolation comment\nreturn 1;\n})()}\n`;\n'
	);
	write(join(root, 'src/view.jsx'), 'export const view = <div />;\n');
	write(join(root, 'src/ignored.generated.svelte.ts'), 'export const ignored = 1;\n');
	write(
		join(root, 'src/generated-client.ts'),
		'// @generated do not edit\nexport const client = 1;\n'
	);
	write(join(root, '.yalc/package/src/dependency.ts'), 'export const dependency = 1;\n');
	write(
		join(root, 'src/nested.ts'),
		'export function outer(values: number[]) {\nconst select = (value: number) => {\nif (value > 0) return value;\nreturn 0;\n};\nreturn values.map(select);\n}\n'
	);
	// `.mts` and `.jsx` are ordinary source and the scanner discovers them, so coverage is complete.
	// This previously asserted two unscanned files, which encoded a gap between the analyzer's
	// source extensions and the scanner's: any repository containing either extension could never
	// reach `pass`, because the coverage check counted files the scan was structurally unable to see.
	const result = run([root], [makeReceipt(root)]);
	assert.equal(result.status, 0, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.notEqual(report.verdict, 'incomplete');
	assert.equal(report.quality.coverage.unscannedProductionFiles, 0);
	// Unchanged: the generated-name and `@generated`-header files, and the `.yalc` tree, are still
	// excluded. Only the coverage gap moved, from two unscanned files to none.
	assert.equal(report.totals.productionFiles, 3);
	assert.equal(report.totals.commentLoc, 1);
	assert.equal(report.distributions.functionCyclomatic.count, 3);
	assert.equal(report.distributions.functionCyclomatic.mean, 1.333);
	assert.equal(report.distributions.functionCyclomatic.max, 2);
});

test('uses true density and refuses meaningless or unrelated baselines', (context) => {
	const root = temporary('score');
	const other = temporary('other');
	context.after(() => {
		rmSync(root, { recursive: true, force: true });
		rmSync(other, { recursive: true, force: true });
	});
	write(join(root, 'package.json'), JSON.stringify({ name: 'score' }));
	write(
		join(root, 'src/index.ts'),
		Array.from({ length: 10 }, (_, index) => `export const v${index} = ${index};`).join('\n') + '\n'
	);
	const receipt = makeReceipt(root, [
		'warning\thigh\tQ3\tone-off\tsrc/index.ts:1: value\tno-bloat'
	]);
	const result = run([root], [receipt]);
	assert.equal(result.status, 1, result.stderr);
	const report = JSON.parse(result.stdout);
	assert.equal(report.scores.staticQuality, 0.99);
	assert.equal(
		report.quality.byPrinciple.find(({ name }) => name === 'no-bloat').perThousandProductionLoc,
		100
	);
	const noBaseline = run([root], [receipt], ['--fail-on-regression']);
	assert.equal(noBaseline.status, 2);
	assert.match(noBaseline.stderr, /requires --baseline/);
	const baseline = join(root, 'baseline.json');
	writeFileSync(baseline, result.stdout);
	write(join(other, 'package.json'), JSON.stringify({ name: 'other' }));
	write(join(other, 'src/index.ts'), 'export const value = 1;\n');
	const unrelated = run(
		[other],
		[makeReceipt(other)],
		['--baseline', baseline, '--fail-on-regression']
	);
	assert.equal(unrelated.status, 2);
	assert.match(unrelated.stderr, /baseline roots do not match/);
});
