// Generated by bolt from the paths under src/system (`systemIndex`, compiler/names.ts): the built-in layer, compiled as
// a workspace is. Never edited; tests/system-layer.test.ts fails when it drifts from the paths.
import type { CollectionSpec } from '../decl/collection.ts';
import type { ModelSpec } from '../decl/model.ts';
import type { RelationshipSpec } from '../decl/names.ts';
import m_approval_request from "./data/model/approval_request/+model.ts";
import m_requestor from "./data/model/requestor/+model.ts";
import m_sys_api_key from "./data/model/sys_api_key/+model.ts";
import m_sys_assignment from "./data/model/sys_assignment/+model.ts";
import m_sys_challenge from "./data/model/sys_challenge/+model.ts";
import m_sys_config from "./data/model/sys_config/+model.ts";
import m_sys_conversation from "./data/model/sys_conversation/+model.ts";
import m_sys_event from "./data/model/sys_event/+model.ts";
import m_sys_file from "./data/model/sys_file/+model.ts";
import m_sys_invitation from "./data/model/sys_invitation/+model.ts";
import m_sys_message from "./data/model/sys_message/+model.ts";
import m_sys_notification from "./data/model/sys_notification/+model.ts";
import m_sys_run from "./data/model/sys_run/+model.ts";
import m_sys_session from "./data/model/sys_session/+model.ts";
import m_sys_team from "./data/model/sys_team/+model.ts";
import m_sys_user from "./data/model/sys_user/+model.ts";
import relationships from "./data/+relationship.ts";
import c_approval_request from "./data/collection/approval_request/+collection.ts";
import c_requestor from "./data/collection/requestor/+collection.ts";
import c_sys_api_key from "./data/collection/sys_api_key/+collection.ts";
import c_sys_assignment from "./data/collection/sys_assignment/+collection.ts";
import c_sys_conversation from "./data/collection/sys_conversation/+collection.ts";
import c_sys_event from "./data/collection/sys_event/+collection.ts";
import c_sys_file from "./data/collection/sys_file/+collection.ts";
import c_sys_invitation from "./data/collection/sys_invitation/+collection.ts";
import c_sys_message from "./data/collection/sys_message/+collection.ts";
import c_sys_notification from "./data/collection/sys_notification/+collection.ts";
import c_sys_run from "./data/collection/sys_run/+collection.ts";
import c_sys_team from "./data/collection/sys_team/+collection.ts";
import c_sys_user from "./data/collection/sys_user/+collection.ts";

/** The layer's names index: each name → its declaration's type, as a workspace's `.norbital/names.ts` maps one. */
export type SystemNames = {
	models: {
		approval_request: typeof m_approval_request;
		requestor: typeof m_requestor;
		sys_api_key: typeof m_sys_api_key;
		sys_assignment: typeof m_sys_assignment;
		sys_challenge: typeof m_sys_challenge;
		sys_config: typeof m_sys_config;
		sys_conversation: typeof m_sys_conversation;
		sys_event: typeof m_sys_event;
		sys_file: typeof m_sys_file;
		sys_invitation: typeof m_sys_invitation;
		sys_message: typeof m_sys_message;
		sys_notification: typeof m_sys_notification;
		sys_run: typeof m_sys_run;
		sys_session: typeof m_sys_session;
		sys_team: typeof m_sys_team;
		sys_user: typeof m_sys_user;
	};
	relationships: typeof relationships;
	collections: {
		approval_request: typeof c_approval_request;
		requestor: typeof c_requestor;
		sys_api_key: typeof c_sys_api_key;
		sys_assignment: typeof c_sys_assignment;
		sys_conversation: typeof c_sys_conversation;
		sys_event: typeof c_sys_event;
		sys_file: typeof c_sys_file;
		sys_invitation: typeof c_sys_invitation;
		sys_message: typeof c_sys_message;
		sys_notification: typeof c_sys_notification;
		sys_run: typeof c_sys_run;
		sys_team: typeof c_sys_team;
		sys_user: typeof c_sys_user;
	};
};
/** The layer's manifest: merged into every workspace's schema plan, catalogue and names. */
export const SYSTEM: {
	models: { readonly [model: string]: ModelSpec };
	relationships: { readonly [key: string]: RelationshipSpec };
	collections: { readonly [collection: string]: CollectionSpec };
} = {
	models: {
		approval_request: m_approval_request,
		requestor: m_requestor,
		sys_api_key: m_sys_api_key,
		sys_assignment: m_sys_assignment,
		sys_challenge: m_sys_challenge,
		sys_config: m_sys_config,
		sys_conversation: m_sys_conversation,
		sys_event: m_sys_event,
		sys_file: m_sys_file,
		sys_invitation: m_sys_invitation,
		sys_message: m_sys_message,
		sys_notification: m_sys_notification,
		sys_run: m_sys_run,
		sys_session: m_sys_session,
		sys_team: m_sys_team,
		sys_user: m_sys_user,
	},
	relationships: relationships,
	collections: {
		approval_request: c_approval_request.spec,
		requestor: c_requestor.spec,
		sys_api_key: c_sys_api_key.spec,
		sys_assignment: c_sys_assignment.spec,
		sys_conversation: c_sys_conversation.spec,
		sys_event: c_sys_event.spec,
		sys_file: c_sys_file.spec,
		sys_invitation: c_sys_invitation.spec,
		sys_message: c_sys_message.spec,
		sys_notification: c_sys_notification.spec,
		sys_run: c_sys_run.spec,
		sys_team: c_sys_team.spec,
		sys_user: c_sys_user.spec,
	},
};
