// repository-health:allow SEM_PARALLEL -- inventory feeds the runner; provider/consumer pair, not parallel implementations.
/**
 * Source inventory and physical LOC classification, ported from `analyze.mjs`.
 *
 * Everything here is deliberately name-based and byte-based: the walk excludes dependency-owned
 * trees by directory name, `.doctorignore` globs, declaration files, compound generated names, and
 * generated headers; the LOC classifiers split physical lines into code, comments, and blanks
 * without ever letting a comment count as code.
 *
 * The scanner-facing half (`SCANNER_SOURCE_EXTENSIONS`, `scannerExcluded`,
 * `scannerInputInventory`) recomputes the receipt's input inventory exactly. The analyzer and the
 * scanner derive their inventories independently and cross-check the digests, so an extension or
 * exclusion known to one and not the other reports every scan as stale instead of silently scoped.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { basename, dirname, extname, join, relative, sep } from 'node:path';
import ts from 'typescript';
import { Option, Schema } from 'effect';
import { ignoredFile } from './ignore.js';

export const SOURCE_EXTENSIONS: ReadonlySet<string> = new Set([
	'.ts',
	'.tsx',
	'.mts',
	'.cts',
	'.js',
	'.jsx',
	'.mjs',
	'.cjs',
	'.svelte'
]);
// Must match the scanner's own discovery exactly. These two lists are compared by count and by
// digest, so an extension in one and not the other reports every scan as stale.
export const SCANNER_SOURCE_EXTENSIONS: ReadonlySet<string> = new Set([
	'.ts',
	'.tsx',
	'.mts',
	'.cts',
	'.js',
	'.jsx',
	'.mjs',
	'.cjs',
	'.svelte'
]);
const IGNORED_DIRECTORIES: ReadonlySet<string> = new Set([
	'.generated',
	'.agents',
	'.claude',
	'.git',
	'.norbital',
	'.open-next',
	'.opencode',
	'.svelte-check',
	'.svelte-kit',
	'.tmp',
	'.turbo',
	'.wrangler',
	'.yalc',
	'build',
	'coverage',
	'dist',
	'generated',
	'migrations',
	'node_modules',
	'playwright-report',
	'release',
	'test-results',
	'vendor'
]);
const GENERATED_HEADER = /^\s*(?:\/\/|\/\*)[^\n]{0,120}(?:@generated|generated by|do not edit)/i;

/** Physical lines classified without letting comments or blank space count as code. */
export type LineCounts = Readonly<{
	physical: number;
	code: number;
	comments: number;
	blank: number;
}>;

/** A selected root together with the collision-safe identity reports use for it. */
export type RootDescription = Readonly<{ path: string; id: string }>;

/** The scanner's recomputed view of one root: production sources, hashed inputs, and the digest. */
export type ScannerInventory = Readonly<{
	sources: ReadonlyArray<string>;
	inputs: ReadonlyArray<string>;
	digest: string;
}>;

export function hasGeneratedHeader(path: string): boolean {
	return GENERATED_HEADER.test(readFileSync(path, 'utf8').slice(0, 500));
}

/** Walk selected roots in lexical order while excluding generated and dependency-owned trees. */
export function collectSourceFiles(roots: ReadonlyArray<string>): Array<string> {
	const files: Array<string> = [];
	// `.doctorignore` is honored here as well as in scannerExcluded. The two walks are cross-checked
	// by digest, so a tree excluded from one and not the other reports as unscanned, not as scoped.
	let currentRoot = '';
	const visit = (directory: string): void => {
		for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) =>
			a.name.localeCompare(b.name)
		)) {
			if (entry.isDirectory() && IGNORED_DIRECTORIES.has(entry.name)) continue;
			const path = join(directory, entry.name);
			if (ignoredFile(currentRoot, relative(currentRoot, path).split(sep).join('/'))) continue;
			if (entry.isDirectory()) visit(path);
			else if (
				entry.isFile() &&
				SOURCE_EXTENSIONS.has(extname(entry.name)) &&
				!/\.d\.(?:ts|mts|cts)$/.test(entry.name) &&
				!/\.(?:generated|gen)(?:\.[^.]+)+$/.test(entry.name) &&
				!hasGeneratedHeader(path)
			)
				files.push(path);
		}
	};
	for (const root of roots) {
		if (!existsSync(root) || !statSync(root).isDirectory())
			throw new Error(`root is not a directory: ${root}`);
		currentRoot = root;
		visit(root);
	}
	return [...new Set(files)].sort();
}

/** Classify mixed `.svelte`/HTML/CSS lines without treating quoted comment markers as comments. */
function mixedLineCounts(source: string): LineCounts {
	const lines = source.split(/\r?\n/);
	if (source.endsWith('\n')) lines.pop();
	const state = { block: false, html: false, quote: '' };
	let code = 0;
	let comments = 0;
	let blank = 0;
	for (const line of lines) {
		let hasCode = false;
		let hasComment = state.block || state.html;
		let escaped = false;
		for (let index = 0; index < line.length; index += 1) {
			const char = line.charAt(index);
			const two = line.slice(index, index + 2);
			const three = line.slice(index, index + 3);
			const four = line.slice(index, index + 4);
			if (state.block) {
				hasComment = true;
				if (two === '*/') {
					state.block = false;
					index += 1;
				}
				continue;
			}
			if (state.html) {
				hasComment = true;
				if (three === '-->') {
					state.html = false;
					index += 2;
				}
				continue;
			}
			if (state.quote !== '') {
				hasCode = true;
				if (escaped) {
					escaped = false;
					continue;
				}
				if (char === '\\') {
					escaped = true;
					continue;
				}
				if (char === state.quote) state.quote = '';
				continue;
			}
			if (two === '//') {
				hasComment = true;
				break;
			}
			if (two === '/*') {
				hasComment = true;
				state.block = true;
				index += 1;
				continue;
			}
			if (four === '<!--') {
				hasComment = true;
				state.html = true;
				index += 3;
				continue;
			}
			if (char === '"' || char === "'" || char === '`') {
				state.quote = char;
				hasCode = true;
				continue;
			}
			if (!/\s/.test(char)) hasCode = true;
		}
		if (state.quote !== '`') state.quote = '';
		if (hasCode) code += 1;
		else if (hasComment) comments += 1;
		else blank += 1;
	}
	return { physical: lines.length, code, comments, blank };
}

/** Classify JS/TS with the compiler scanner so template-expression comments remain comments. */
function scriptLineCounts(source: string): LineCounts {
	const lines = source.split(/\r?\n/);
	if (source.endsWith('\n')) lines.pop();
	const code = new Set<number>();
	const comments = new Set<number>();
	const starts = [0];
	for (let index = 0; index < source.length; index += 1)
		if (source.charAt(index) === '\n') starts.push(index + 1);
	const lineAt = (position: number): number => {
		let low = 0;
		let high = starts.length - 1;
		while (low <= high) {
			const middle = Math.floor((low + high) / 2);
			if ((starts[middle] ?? 0) <= position) low = middle + 1;
			else high = middle - 1;
		}
		return Math.max(0, high);
	};
	const mark = (set: Set<number>, start: number, end: number): void => {
		if (end <= start) return;
		const first = lineAt(start);
		const last = lineAt(Math.max(start, end - 1));
		for (let line = first; line <= last && line < lines.length; line += 1) set.add(line);
	};
	const scanner = ts.createScanner(ts.ScriptTarget.Latest, false, ts.LanguageVariant.JSX, source);
	for (
		let token = scanner.scan();
		token !== ts.SyntaxKind.EndOfFileToken;
		token = scanner.scan()
	) {
		const start = scanner.getTokenPos();
		const end = scanner.getTextPos();
		if (
			token === ts.SyntaxKind.WhitespaceTrivia ||
			token === ts.SyntaxKind.NewLineTrivia ||
			token === ts.SyntaxKind.ConflictMarkerTrivia
		)
			continue;
		if (
			token === ts.SyntaxKind.SingleLineCommentTrivia ||
			token === ts.SyntaxKind.MultiLineCommentTrivia
		)
			mark(comments, start, end);
		else mark(code, start, end);
	}
	let commentLines = 0;
	let blank = 0;
	for (let line = 0; line < lines.length; line += 1) {
		if (code.has(line)) continue;
		if (comments.has(line)) commentLines += 1;
		else blank += 1;
	}
	return { physical: lines.length, code: code.size, comments: commentLines, blank };
}

/** Classify physical lines: `.svelte` takes the mixed classifier, everything else the compiler's. */
export function lineCounts(path: string, source: string): LineCounts {
	return path.endsWith('.svelte') ? mixedLineCounts(source) : scriptLineCounts(source);
}

/** Extract component scripts for compiler analysis while LOC continues to cover the whole `.svelte` file. */
export function analyzableSource(path: string, source: string): string {
	if (!path.endsWith('.svelte')) return source;
	return [...source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)]
		.map((match) => match[1] ?? '')
		.join('\n');
}

/** Recognize tests independently of package layout so production metrics cannot be padded by them. */
export function isTestPath(path: string): boolean {
	const normalized = path.split(sep).join('/');
	return (
		/\/(?:test|tests|e2e|__tests__)\//.test(normalized) ||
		/\.(?:test|spec)\.[^.]+$/.test(normalized)
	);
}

/** Whether a path belongs to the scanner's complete production source inventory. */
export function scannerExcluded(root: string, file: string): boolean {
	return (
		ignoredFile(root, file) ||
		/\.d\.(?:ts|mts|cts)$/.test(file) ||
		/(?:^|\/)[^/]+\.(?:generated|gen)(?:\.svelte)?\.(?:[cm]?[jt]sx?|svelte)$/.test(file) ||
		/(^|\/)(node_modules|\.yalc|build|dist|coverage|generated|\.generated|\.svelte-check|\.svelte-kit(?:-e2e)?|\.tmp|\.data|\.agents|\.opencode)(\/|$)/.test(
			file
		) ||
		/(^|\/)(test|tests|e2e|__tests__)(\/|$)/.test(file) ||
		/\.(test|spec)\.[^.]+$/.test(file) ||
		hasGeneratedHeader(join(root, file))
	);
}

const ExternalErrorShape = Schema.Union([
	Schema.Struct({ code: Schema.Unknown }),
	Schema.Struct({ status: Schema.Unknown })
]);

function externalErrorCode(error: unknown): { code?: unknown; status?: unknown } {
	const decoded = Schema.decodeUnknownOption(ExternalErrorShape)(error);
	return Option.isSome(decoded) ? decoded.value : {};
}

/** Recompute the scanner input inventory exactly, including manifests and compiler configuration. */
export function scannerInputInventory(root: string): ScannerInventory {
	let discovered: Array<string>;
	let git = false;
	try {
		execFileSync('git', ['rev-parse', '--is-inside-work-tree'], { cwd: root, stdio: 'ignore' });
		git = true;
	} catch {
		/* A non-git tree is discovered below without changing the inventory contract. */
	}
	if (git) {
		const patterns = [...SCANNER_SOURCE_EXTENSIONS].map((extension) => `*${extension}`);
		const tracked = execFileSync('git', ['ls-files', '-z', '--', ...patterns], {
			cwd: root,
			encoding: 'utf8'
		});
		const untracked = execFileSync(
			'git',
			['ls-files', '--others', '--exclude-standard', '-z', '--', ...patterns],
			{ cwd: root, encoding: 'utf8' }
		);
		discovered = `${tracked}${untracked}`.split('\0');
	} else {
		const globs = [...SCANNER_SOURCE_EXTENSIONS].flatMap((extension) => ['-g', `*${extension}`]);
		try {
			discovered = execFileSync('rg', ['--files', '-0', ...globs], {
				cwd: root,
				encoding: 'utf8'
			}).split('\0');
		} catch (error) {
			const external = externalErrorCode(error);
			if (external.code === 'ENOENT') {
				discovered = collectSourceFiles([root]).map((file) =>
					relative(root, file).split(sep).join('/')
				);
			} else if (external.status === 1) discovered = [];
			else throw error;
		}
	}
	const sources = [...new Set(discovered)]
		.filter(Boolean)
		.map((file) => file.split(sep).join('/'))
		.filter((file) => existsSync(join(root, file)) && !scannerExcluded(root, file))
		.sort();
	const inputs = new Set(sources);
	if (existsSync(join(root, '.doctorignore'))) inputs.add('.doctorignore');
	for (const file of sources) {
		let directory = dirname(join(root, file));
		while (directory === root || directory.startsWith(`${root}${sep}`)) {
			for (const name of ['package.json', 'tsconfig.json', 'jsconfig.json']) {
				const candidate = join(directory, name);
				if (existsSync(candidate)) inputs.add(relative(root, candidate).split(sep).join('/'));
			}
			if (directory === root) break;
			directory = dirname(directory);
		}
	}
	const digest = createHash('sha256');
	for (const file of [...inputs].sort()) {
		const bytes = readFileSync(join(root, file));
		const fileDigest = createHash('sha256').update(bytes).digest('hex');
		digest.update(`${file}\0${fileDigest}\n`, 'utf8');
	}
	return { sources, inputs: [...inputs].sort(), digest: `sha256:${digest.digest('hex')}` };
}

/** Give roots collision-safe report identities without depending on argument order. */
export function describeRoots(roots: ReadonlyArray<string>): Array<RootDescription> {
	const counts = new Map<string, number>();
	for (const root of roots) counts.set(basename(root), (counts.get(basename(root)) ?? 0) + 1);
	return roots.map((path) => ({
		path,
		id:
			counts.get(basename(path)) === 1
				? basename(path)
				: `${basename(path)}-${createHash('sha256').update(path).digest('hex').slice(0, 8)}`
	}));
}
