/**
 * Run authored rules over a repository's sources.
 *
 * This is the syntactic tier: rules here are per-file and pure, so they parallelise and cache by
 * construction, and a repository that loads no packs pays nothing.
 *
 * Dispatch is by syntax kind. Every node is visited once and only the rules that asked for that
 * kind are consulted, rather than every rule's guard running against every node.
 */
import { getErrorMessage } from '@norbital-ai/std';
import { Effect } from 'effect';
import * as Result from 'effect/Result';
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import ts from 'typescript';
import { clearIgnoreCache, ignoredFile, ignoredRule } from '../engine/scripts/ignore.mjs';
import type { Finding } from './index.js';
import { PRINCIPLE_ORDER, type NodeKind, type Rule, type RuleContext } from './rules.js';

const SOURCE = /\.(?:[mc]?tsx?|[mc]?jsx?|svelte)$/;
const IGNORED =
	/(^|\/)(node_modules|\.yalc|\.git|build|dist|coverage|generated|\.generated|\.svelte-check|\.svelte-kit|\.tmp|\.norbital|\.turbo|\.agents)(\/|$)/;
const TEST = /(^|\/)(test|tests|e2e|__tests__)(\/|$)|\.(test|spec)\.[^.]+$/;
const GENERATED_HEADER = /^\s*(?:\/\/|\/\*)[^\n]{0,120}(?:@generated|generated by|do not edit)/i;

/** Translate a `*` / `**` path pattern into an anchored expression. */
function patternToRegExp(pattern: string): RegExp {
	const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, '\\$&');
	const expression = escaped
		.replace(/\*\*\//g, 'SLASH')
		.replace(/\*\*/g, 'ANY')
		.replace(/\*/g, '[^/]*')
		.replace(/SLASH/g, '(?:.*/)?')
		.replace(/ANY/g, '.*');
	return new RegExp(`^${expression}$`);
}

function matchesAny(file: string, patterns: ReadonlyArray<string> | undefined): boolean {
	if (patterns === undefined || patterns.length === 0) return false;
	return patterns.some((pattern) => patternToRegExp(pattern).test(file));
}

export type SourceFileOptions = Readonly<{
	readonly includeTests?: boolean | undefined;
	/** Repository-relative files or directories. Directories select their descendants. */
	readonly paths?: ReadonlyArray<string> | undefined;
}>;

/** Deterministic source discovery when neither git nor ripgrep is installed. */
function walkedFiles(root: string): ReadonlyArray<string> {
	const files: Array<string> = [];
	const visit = (directory: string): void => {
		for (const entry of readdirSync(directory, { withFileTypes: true }).sort((left, right) =>
			left.name.localeCompare(right.name)
		)) {
			const absolute = join(directory, entry.name);
			const local = relative(root, absolute).split(sep).join('/');
			if (entry.isDirectory()) {
				if (!IGNORED.test(`${local}/`)) visit(absolute);
			} else if (entry.isFile()) files.push(local);
		}
	};
	visit(root);
	return files;
}

function gitFiles(root: string): Array<string> {
	execFileSync('git', ['rev-parse', '--is-inside-work-tree'], { cwd: root, stdio: 'ignore' });
	const tracked = execFileSync('git', ['ls-files', '-z'], { cwd: root, encoding: 'utf8' });
	const untracked = execFileSync('git', ['ls-files', '--others', '--exclude-standard', '-z'], {
		cwd: root,
		encoding: 'utf8'
	});
	return `${tracked}${untracked}`.split('\0').filter(Boolean);
}

function nonGitFiles(root: string): ReadonlyArray<string> {
	const scanned = Effect.runSync(
		Effect.result(Effect.try(() => execFileSync('rg', ['--files', '-0'], { cwd: root, encoding: 'utf8' })))
	);
	return Result.match(scanned, {
		onSuccess: (out) => out.split('\0').filter(Boolean),
		onFailure: (error) => {
			// The caught error nests the spawn failure; ENOENT means "rg is not installed" and a
			// status-1 exit means "no files", both of which are results rather than failures.
			const cause = (error as { cause?: unknown })?.cause as { code?: string; status?: number } | undefined;
			if (cause?.code === 'ENOENT') return walkedFiles(root);
			if (cause?.status === 1) return [];
			throw error;
		}
	});
}

function discoveredFiles(root: string): ReadonlyArray<string> {
	const listed = Effect.runSync(Effect.result(Effect.try(() => gitFiles(root))));
	return Result.getOrElse(listed, () => nonGitFiles(root));
}

/** Repository sources, discovered through git so ignored files never reach a rule. */
export function sourceFiles(root: string, options: SourceFileOptions = {}): ReadonlyArray<string> {
	const discovered = discoveredFiles(root);
	clearIgnoreCache(root);
	const selected = options.paths?.map((path) => path.replace(/^\.\//, '').replace(/\/$/, ''));
	return [
		...new Set(
			discovered
				.map((file) => file.split(sep).join('/'))
				.filter(
					(file) =>
						SOURCE.test(file) &&
						!IGNORED.test(file) &&
						!/\.d\.[cm]?ts$/.test(file) &&
						(options.includeTests || !TEST.test(file)) &&
						!ignoredFile(root, file) &&
						// git lists staged deletions and index entries whose file is gone. A path that
						// cannot be read is not a source, and must not abort the whole scan.
						existsSync(join(root, file)) &&
						!GENERATED_HEADER.test(readFileSync(join(root, file), 'utf8').slice(0, 500)) &&
						(selected === undefined ||
							selected.some((path) => path === '' || file === path || file.startsWith(`${path}/`)))
				)
		)
	].sort();
}

/**
 * The `<script>` body of a Svelte component, padded so offsets still map to real lines.
 *
 * Padding rather than slicing keeps every reported line number correct against the original file,
 * which matters because the location string is what a person clicks.
 */
export function svelteScript(source: string): string | undefined {
	// Every block, not the first: a component with `<script module>` above `<script>` kept only the
	// module block, so the instance script — where the imports and the state live — was invisible to
	// every rule. 65 components in `oss` alone are shaped that way.
	//
	// Non-script regions become newlines rather than being dropped, so a reported line is the line
	// in the file the person opens.
	const pattern = /<script\b[^>]*>([\s\S]*?)<\/script>/g;
	let assembled = '';
	let cursor = 0;
	let found = false;
	for (let match = pattern.exec(source); match !== null; match = pattern.exec(source)) {
		const body = match[1] ?? '';
		const opensAt = match.index + match[0].indexOf(body);
		assembled += '\n'.repeat(source.slice(cursor, opensAt).split('\n').length - 1) + body;
		cursor = opensAt + body.length;
		found = true;
	}
	return found ? assembled : undefined;
}

function scriptKind(file: string): ts.ScriptKind {
	if (file.endsWith('.tsx')) return ts.ScriptKind.TSX;
	if (file.endsWith('.jsx')) return ts.ScriptKind.JSX;
	if (/\.(?:m|c)?js$/.test(file)) return ts.ScriptKind.JS;
	return ts.ScriptKind.TS;
}

function collectImports(sourceFile: ts.SourceFile): Map<string, Set<string>> {
	const imports = new Map<string, Set<string>>();
	for (const statement of sourceFile.statements) {
		if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier))
			continue;
		const specifier = statement.moduleSpecifier.text;
		const names = imports.get(specifier) ?? new Set<string>();
		const bindings = statement.importClause?.namedBindings;
		if (statement.importClause?.name) names.add(statement.importClause.name.text);
		if (bindings && ts.isNamedImports(bindings))
			for (const element of bindings.elements)
				names.add((element.propertyName ?? element.name).text);
		if (bindings && ts.isNamespaceImport(bindings)) names.add(bindings.name.text);
		imports.set(specifier, names);
	}
	return imports;
}

function calleeName(node: ts.Node): string | undefined {
	if (!ts.isCallExpression(node) && !ts.isNewExpression(node)) return undefined;
	const target = node.expression;
	if (ts.isIdentifier(target)) return target.text;
	if (ts.isPropertyAccessExpression(target)) {
		const parts: Array<string> = [target.name.text];
		let current: ts.Expression = target.expression;
		while (ts.isPropertyAccessExpression(current)) {
			parts.unshift(current.name.text);
			current = current.expression;
		}
		if (ts.isIdentifier(current)) parts.unshift(current.text);
		return parts.join('.');
	}
	return undefined;
}

export type RunOptions = Readonly<{
	readonly root: string;
	readonly rules: ReadonlyArray<Rule>;
	/** Restrict the run to these repository-relative files. Defaults to the whole repository. */
	readonly files?: ReadonlyArray<string> | undefined;
}>;

/**
 * Drop a finding when a rule that dominates it reported the same defect at the same site.
 *
 * Two rules firing on one line are usually two claims about one line, not two defects: `v as unknown
 * as number` is a double assertion (`R3b`) and an assertion to `unknown` (`R3e`), but fixing it once
 * removes both. Counting it twice inflates the debt and makes the sharper rule look redundant.
 *
 * Dominance is declared by the dominating rule, so a pack can subsume a rule it did not write.
 */
function applyDominance(
	findings: ReadonlyArray<Finding>,
	site: ReadonlyMap<Finding, string>,
	rules: ReadonlyArray<Rule>
): Array<Finding> {
	const dominated = new Map<string, ReadonlyArray<string>>();
	for (const rule of rules)
		if (rule.dominates !== undefined && rule.dominates.length > 0)
			dominated.set(rule.id, rule.dominates);
	if (dominated.size === 0) return [...findings];

	// Which rules won a site, so a dominated finding there can be recognised.
	const winners = new Map<string, Set<string>>();
	for (const finding of findings) {
		const at = site.get(finding);
		if (at === undefined || !dominated.has(finding.rule)) continue;
		const held = winners.get(at) ?? new Set<string>();
		held.add(finding.rule);
		winners.set(at, held);
	}

	return findings.filter((finding) => {
		const at = site.get(finding);
		if (at === undefined) return true;
		const held = winners.get(at);
		if (held === undefined) return true;
		for (const winner of held) {
			if (winner === finding.rule) continue;
			if (dominated.get(winner)?.includes(finding.rule) === true) return false;
		}
		return true;
	});
}

/** Execute every rule over every selected file and return the findings in catalogue order. */
export function runRules(options: RunOptions): ReadonlyArray<Finding> {
	if (options.rules.length === 0) return [];

	const byKind = new Map<ts.SyntaxKind, Array<Rule>>();
	for (const rule of options.rules)
		for (const kind of rule.when) {
			const syntax = ts.SyntaxKind[kind as NodeKind];
			const bucket = byKind.get(syntax) ?? [];
			bucket.push(rule);
			byKind.set(syntax, bucket);
		}

	const findings: Array<Finding> = [];
	/** Where each finding was reported, for the dominance pass below. */
	const site = new Map<Finding, string>();
	const files = options.files ?? sourceFiles(options.root);

	for (const file of files) {
		const absolute = join(options.root, file);
		if (!existsSync(absolute)) continue;
		const raw = readFileSync(absolute, 'utf8');
		// A component with no `<script>` is still a component: its markup is what the layout rules
		// read. Passing `undefined` here made `ts.createSourceFile` throw, the file was skipped
		// whole, and a markup-only rule could never fire on a script-less component.
		const text = file.endsWith('.svelte') ? (svelteScript(raw) ?? '') : raw;
		if (text === undefined) continue;

		const applicable = options.rules.filter(
			(rule) =>
				(rule.files === undefined || matchesAny(file, rule.files)) &&
				!matchesAny(file, rule.ignore) &&
				// `.doctorignore` scopes authored rules exactly as it scopes built-in ones; a repository
				// should not have to know which mechanism produced a finding in order to silence it.
				!ignoredRule(options.root, file, rule.id)
		);
		if (applicable.length === 0) continue;
		const allowed = new Set(applicable);

		const parsed = Effect.runSync(
			Effect.result(Effect.try(() => ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, scriptKind(file))))
		);
		const sourceFile = Result.getOrElse(parsed, () => undefined);
		if (sourceFile === undefined) continue;

		let importCache: Map<string, Set<string>> | undefined;
		let active: Rule | undefined;
		let current: ts.Node | undefined;

		const context: RuleContext = {
			file,
			source: raw,
			root: options.root,
			sourceFile,
			ts,
			text: (node) => node.getText(sourceFile),
			ancestors: (node) => {
				const chain: Array<ts.Node> = [];
				for (let parent = node.parent; parent; parent = parent.parent) chain.push(parent);
				return chain;
			},
			calleeName,
			imports: () => (importCache ??= collectImports(sourceFile)),
			importsFrom: (specifier) => {
				importCache ??= collectImports(sourceFile);
				for (const key of importCache.keys())
					if (key === specifier || key.startsWith(`${specifier}/`)) return true;
				return false;
			},
			report: (node, evidence) => {
				if (active === undefined) return;
				const position = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
				const line = raw.split('\n')[position.line] ?? '';
				const reported: Finding = {
					severity: active.severity,
					confidence: active.confidence ?? 'high',
					rule: active.id,
					summary: active.summary,
					location: `${file}:${position.line + 1}: ${line.trim()}${evidence ? ` [${evidence}]` : ''}`,
					// Canonical order, not declaration order: the report groups by principle and the receipt
					// validates the sequence, so an author listing them in any order still produces a
					// catalogue row the analyzer accepts.
					principles: PRINCIPLE_ORDER.filter((principle) => active!.principles.includes(principle))
				};
				// Remember the site rather than re-parsing `location`: the dominance pass needs the
				// exact file and line, and a formatted string is not a data structure.
				site.set(reported, `${file}:${position.line + 1}`);
				findings.push(reported);
			},
			reportAt: (line, evidence) => {
				if (active === undefined) return;
				const lines = raw.split('\n');
				const index = Math.min(Math.max(line, 1), lines.length) - 1;
				const reported: Finding = {
					severity: active.severity,
					confidence: active.confidence ?? 'high',
					rule: active.id,
					summary: active.summary,
					location: `${file}:${index + 1}: ${(lines[index] ?? '').trim()}${evidence ? ` [${evidence}]` : ''}`,
					principles: PRINCIPLE_ORDER.filter((principle) => active!.principles.includes(principle))
				};
				site.set(reported, `${file}:${index + 1}`);
				findings.push(reported);
			}
		};

		const visit = (node: ts.Node): void => {
			const matched = byKind.get(node.kind);
			if (matched) {
				current = node;
				for (const rule of matched) {
					if (!allowed.has(rule)) continue;
					active = rule;
					const outcome = Effect.runSync(
						Effect.result(Effect.try(() => rule.check(node, context)))
					);
				if (Result.isFailure(outcome))
					// A defective rule must not take the audit down with it, and must not pass
					// silently either — it becomes a finding against itself.
					findings.push(Result.match(outcome, {
						onFailure: (error) => {
							const cause = (error as { cause?: unknown })?.cause ?? error;
							const detail = getErrorMessage(cause);
							return {
								severity: 'error',
								confidence: 'high',
								rule: 'RULE',
								summary: 'an authored rule threw while checking a node',
								location: `${file}:1: ${rule.id} [${detail}]`,
								principles: ['testability']
							};
						},
						onSuccess: () => undefined
					}) as never);
					active = undefined;
				}
			}
			ts.forEachChild(node, visit);
		};
		visit(sourceFile);
		void current;
	}

	const order = { error: 0, warning: 1, hint: 2 } as const;
	return applyDominance(findings, site, options.rules).sort(
		(a, b) =>
			order[a.severity] - order[b.severity] ||
			a.rule.localeCompare(b.rule) ||
			a.location.localeCompare(b.location)
	);
}
